use std::ffi::OsStr;
use std::fs;
use std::path::Path;
use std::process::{Command, Output};

use tempfile::TempDir;

fn base(directory: &Path, home: &Path, arguments: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_base"))
        .arg("--directory")
        .arg(directory)
        .args(arguments)
        .env("BASE_HOME", home)
        .output()
        .expect("base command runs")
}

fn base_with_path(directory: &Path, home: &Path, path: &OsStr, arguments: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_base"))
        .arg("--directory")
        .arg(directory)
        .args(arguments)
        .env("BASE_HOME", home)
        .env("PATH", path)
        .output()
        .expect("base command runs")
}

fn success(directory: &Path, home: &Path, arguments: &[&str]) -> Output {
    let output = base(directory, home, arguments);
    assert!(
        output.status.success(),
        "base {arguments:?} failed:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    output
}

#[test]
fn walking_skeleton_syncs_and_detects_drift() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();

    success(project.path(), home.path(), &["init", "--project"]);
    success(project.path(), home.path(), &["check"]);
    success(project.path(), home.path(), &["sync"]);
    success(project.path(), home.path(), &["sync", "--check"]);

    assert!(project.path().join("CLAUDE.md").is_file());
    assert!(project.path().join("AGENTS.md").is_file());
    assert!(
        project
            .path()
            .join(".github/prompts/build.prompt.md")
            .is_file()
    );
    let codex_skill =
        fs::read_to_string(project.path().join(".agents/skills/build/SKILL.md")).unwrap();
    assert!(codex_skill.starts_with("---\n"));
    assert!(codex_skill.contains("generated by base sync"));
    let claude_settings = fs::read_to_string(project.path().join(".claude/settings.json")).unwrap();
    let settings: serde_json::Value = serde_json::from_str(&claude_settings).unwrap();
    assert!(settings.get("hooks").is_some());
    let matchers: Vec<&str> = settings["hooks"]["PreToolUse"]
        .as_array()
        .unwrap()
        .iter()
        .filter_map(|entry| entry["matcher"].as_str())
        .collect();
    assert!(matchers.contains(&"Bash"));
    assert!(matchers.contains(&"mcp__github__.*"));
    assert!(settings.get("_base_generated").is_none());
    assert!(
        project
            .path()
            .join(".agents/skills/build/SKILL.md")
            .is_file()
    );

    fs::write(project.path().join("CLAUDE.md"), "hand edit\n").unwrap();
    let drift = base(project.path(), home.path(), &["sync", "--check", "--json"]);
    assert!(!drift.status.success());
    let error: serde_json::Value = serde_json::from_slice(&drift.stderr).unwrap();
    assert_eq!(error["ok"], false);
    assert!(error["error"].as_str().unwrap().contains("out of sync"));
    assert!(
        !base(project.path(), home.path(), &["sync"])
            .status
            .success()
    );
    success(project.path(), home.path(), &["sync", "--force"]);
    success(project.path(), home.path(), &["sync", "--check"]);
}

#[test]
fn init_preserves_config_and_history() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    success(project.path(), home.path(), &["sync"]);
    let config_before = fs::read_to_string(project.path().join(".base/base.toml")).unwrap();
    fs::write(
        project.path().join(".base/history.jsonl"),
        "{\"slug\":\"existing\"}\n",
    )
    .unwrap();

    success(project.path(), home.path(), &["init", "--project"]);

    assert_eq!(
        fs::read_to_string(project.path().join(".base/base.toml")).unwrap(),
        config_before
    );
    assert_eq!(
        fs::read_to_string(project.path().join(".base/history.jsonl")).unwrap(),
        "{\"slug\":\"existing\"}\n"
    );
}

#[test]
fn removing_a_gate_removes_its_generated_bindings() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    success(project.path(), home.path(), &["sync"]);
    assert!(project.path().join(".claude/settings.json").is_file());
    assert!(project.path().join(".codex/rules/base.rules").is_file());

    let mut config = base_cli::config::Config::load(project.path()).unwrap();
    config
        .gates
        .retain(|gate| gate.id != "never-push-default-branch");
    config.save(project.path()).unwrap();
    success(project.path(), home.path(), &["sync"]);
    success(project.path(), home.path(), &["sync", "--check"]);

    assert!(!project.path().join(".claude/settings.json").exists());
    assert!(!project.path().join(".codex/rules/base.rules").exists());
    assert!(project.path().join("CLAUDE.md").is_file());
}

#[test]
fn work_new_scaffolds_folder_item() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    let created = success(
        project.path(),
        home.path(),
        &[
            "work",
            "new",
            "Ship a useful thing",
            "--tags",
            "v1,test",
            "--criterion",
            "The CLI ships",
            "--criterion",
            " Tests pass ",
            "--json",
        ],
    );
    let created: serde_json::Value = serde_json::from_slice(&created.stdout).unwrap();
    assert_eq!(created["id"], "W-0001");
    assert_eq!(created["status"], "todo");
    assert_eq!(created["verdict"], "pending");
    assert_eq!(created["files"], serde_json::json!([]));

    let item = project
        .path()
        .join(".base/work/W-0001-ship-a-useful-thing/item.md");
    assert!(item.is_file());
    let raw = fs::read_to_string(item).unwrap();
    assert!(raw.contains("status: todo"));
    assert!(raw.contains("verdict: pending"));
    assert!(raw.contains("## Acceptance Criteria"));
    assert!(raw.contains("- [ ] The CLI ships"));
    assert!(raw.contains("- [ ] Tests pass"));

    let shown = success(
        project.path(),
        home.path(),
        &["work", "show", "W-0001", "--json"],
    );
    let value: serde_json::Value = serde_json::from_slice(&shown.stdout).unwrap();
    assert_eq!(value["title"], "Ship a useful thing");
    assert_eq!(value["tags"], serde_json::json!(["v1", "test"]));
    assert_eq!(value["body"], created["body"]);
}

#[test]
fn work_move_transitions_and_verdict_rules() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    success(
        project.path(),
        home.path(),
        &["work", "new", "Transition item", "--criterion", "Ready"],
    );
    success(
        project.path(),
        home.path(),
        &["work", "move", "W-0001", "doing"],
    );

    let missing_verdict = base(
        project.path(),
        home.path(),
        &["work", "move", "W-0001", "done"],
    );
    assert!(!missing_verdict.status.success());
    assert!(
        String::from_utf8_lossy(&missing_verdict.stderr)
            .contains("moving W-0001 to done requires --verdict pass|fail")
    );

    success(
        project.path(),
        home.path(),
        &["work", "move", "W-0001", "done", "--verdict", "pass"],
    );
    let reviewed = success(
        project.path(),
        home.path(),
        &["work", "move", "W-0001", "review", "--json"],
    );
    let reviewed: serde_json::Value = serde_json::from_slice(&reviewed.stdout).unwrap();
    assert_eq!(reviewed["status"], "review");
    assert_eq!(reviewed["verdict"], "pending");

    let misplaced_verdict = base(
        project.path(),
        home.path(),
        &["work", "move", "W-0001", "review", "--verdict", "pass"],
    );
    assert!(!misplaced_verdict.status.success());
    assert!(
        String::from_utf8_lossy(&misplaced_verdict.stderr)
            .contains("--verdict only applies when moving to done")
    );
}

#[test]
fn work_move_requires_acceptance_criteria() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    success(
        project.path(),
        home.path(),
        &["work", "new", "Criteria gate"],
    );

    let empty = base(
        project.path(),
        home.path(),
        &["work", "move", "W-0001", "doing"],
    );
    assert!(!empty.status.success());
    assert!(String::from_utf8_lossy(&empty.stderr).contains("W-0001 has no acceptance criteria"));

    let item = project
        .path()
        .join(".base/work/W-0001-criteria-gate/item.md");
    let source = fs::read_to_string(&item)
        .unwrap()
        .replace("## Acceptance Criteria", "## Notes");
    fs::write(item, source).unwrap();
    let missing = base(
        project.path(),
        home.path(),
        &["work", "move", "W-0001", "doing"],
    );
    assert!(!missing.status.success());
    assert!(
        String::from_utf8_lossy(&missing.stderr)
            .contains("W-0001 is missing its ## Acceptance Criteria section")
    );
}

#[test]
fn work_board_renders_columns() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    success(
        project.path(),
        home.path(),
        &["work", "new", "Todo card", "--criterion", "Queued"],
    );
    success(
        project.path(),
        home.path(),
        &["work", "new", "Done card", "--criterion", "Shipped"],
    );
    let done_item = project.path().join(".base/work/W-0002-done-card/item.md");
    let source = fs::read_to_string(&done_item)
        .unwrap()
        .replace("- [ ] Shipped", "- [x] Shipped");
    fs::write(done_item, source).unwrap();
    success(
        project.path(),
        home.path(),
        &["work", "move", "W-0002", "done", "--verdict", "pass"],
    );

    let rendered = success(project.path(), home.path(), &["work", "board"]);
    let rendered = String::from_utf8(rendered.stdout).unwrap();
    assert!(rendered.contains("TODO (1)"));
    assert!(rendered.contains("REVIEW (0)"));
    assert!(rendered.contains("W-0002 ✓"));

    let json = success(project.path(), home.path(), &["work", "board", "--json"]);
    let json: serde_json::Value = serde_json::from_slice(&json.stdout).unwrap();
    assert_eq!(json["todo"].as_array().unwrap().len(), 1);
    assert_eq!(json["doing"], serde_json::json!([]));
    assert_eq!(json["review"], serde_json::json!([]));
    assert_eq!(json["done"][0]["verdict"], "pass");
}

#[test]
fn work_list_validates_status_filter() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    success(
        project.path(),
        home.path(),
        &["work", "new", "Doing item", "--criterion", "Started"],
    );
    success(
        project.path(),
        home.path(),
        &["work", "move", "W-0001", "doing"],
    );
    success(
        project.path(),
        home.path(),
        &["work", "new", "Todo item", "--criterion", "Queued"],
    );

    let filtered = success(
        project.path(),
        home.path(),
        &["work", "list", "--status", "doing", "--json"],
    );
    let filtered: serde_json::Value = serde_json::from_slice(&filtered.stdout).unwrap();
    assert_eq!(filtered.as_array().unwrap().len(), 1);
    assert_eq!(filtered[0]["id"], "W-0001");

    let invalid = base(
        project.path(),
        home.path(),
        &["work", "list", "--status", "open"],
    );
    assert!(!invalid.status.success());
    let stderr = String::from_utf8_lossy(&invalid.stderr);
    assert!(stderr.contains("possible values"));
    assert!(stderr.contains("todo"));
    assert!(stderr.contains("doing"));
    assert!(stderr.contains("review"));
    assert!(stderr.contains("done"));
}

#[test]
fn work_ignores_attachments_and_strays() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    success(
        project.path(),
        home.path(),
        &["work", "new", "Attached item", "--criterion", "Documented"],
    );
    let work = project.path().join(".base/work");
    let item = work.join("W-0001-attached-item");
    fs::create_dir_all(item.join("attachments")).unwrap();
    fs::write(item.join("attachments/data.txt"), "data\n").unwrap();
    fs::write(item.join("notes.md"), "notes\n").unwrap();
    fs::write(work.join("random.md"), "legacy\n").unwrap();
    fs::create_dir(work.join("W-0009-empty")).unwrap();

    let listed = base(project.path(), home.path(), &["work", "list", "--json"]);
    assert!(listed.status.success());
    let listed_json: serde_json::Value = serde_json::from_slice(&listed.stdout).unwrap();
    assert_eq!(listed_json.as_array().unwrap().len(), 1);
    assert_eq!(
        listed_json[0]["files"],
        serde_json::json!([
            ".base/work/W-0001-attached-item/attachments/data.txt",
            ".base/work/W-0001-attached-item/notes.md"
        ])
    );
    let stderr = String::from_utf8_lossy(&listed.stderr);
    assert!(stderr.contains("warning: ignoring legacy work file .base/work/random.md"));
    assert!(
        stderr.contains("warning: ignoring work directory without item.md .base/work/W-0009-empty")
    );
}

#[test]
fn work_new_sequences_ids_past_stray_folders() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    fs::create_dir(project.path().join(".base/work/W-0007-ghost")).unwrap();

    let created = success(
        project.path(),
        home.path(),
        &[
            "work",
            "new",
            "Next item",
            "--criterion",
            "Sequenced",
            "--json",
        ],
    );
    let created: serde_json::Value = serde_json::from_slice(&created.stdout).unwrap();
    assert_eq!(created["id"], "W-0008");
    assert!(
        project
            .path()
            .join(".base/work/W-0008-next-item/item.md")
            .is_file()
    );
}

#[test]
fn log_reads_aborted_runs() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    let run = project.path().join(".base/runs/2026-07-14-aborted-example");
    fs::create_dir_all(&run).unwrap();
    fs::write(run.join("task.md"), "# Aborted example\n").unwrap();
    fs::write(
        project.path().join(".base/history.jsonl"),
        "{\"slug\":\"2026-07-14-aborted-example\",\"date\":\"2026-07-14\",\"pipeline\":\"build\",\"harness\":\"codex\",\"outcome\":\"aborted\",\"paths\":[\".base/runs/2026-07-14-aborted-example/task.md\"]}\n",
    )
    .unwrap();

    let listed = success(project.path(), home.path(), &["log", "--json"]);
    let history: serde_json::Value = serde_json::from_slice(&listed.stdout).unwrap();
    assert_eq!(history[0]["outcome"], "aborted");
    let shown = success(
        project.path(),
        home.path(),
        &["log", "2026-07-14-aborted-example", "--json"],
    );
    let report: serde_json::Value = serde_json::from_slice(&shown.stdout).unwrap();
    assert_eq!(report["history"][0]["outcome"], "aborted");
    assert_eq!(
        report["files"][0],
        ".base/runs/2026-07-14-aborted-example/task.md"
    );
}

#[test]
fn check_downgrades_claude_hook_enforcement_when_base_is_off_path() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);

    let claude_denial = |report: &serde_json::Value| {
        report["enforcement"]
            .as_array()
            .unwrap()
            .iter()
            .find(|row| row["gate"] == "never-push-default-branch" && row["target"] == "claude")
            .expect("claude standing-denial row exists")["fidelity"]
            .clone()
    };

    let empty_dir = TempDir::new().unwrap();
    let missing = base_with_path(
        project.path(),
        home.path(),
        empty_dir.path().as_os_str(),
        &["check", "--json"],
    );
    assert!(missing.status.success());
    let report: serde_json::Value = serde_json::from_slice(&missing.stdout).unwrap();
    assert_eq!(claude_denial(&report), "assisted");
    let warning = report["warnings"][0].as_str().unwrap();
    assert!(warning.contains("PATH"));
    assert!(warning.contains("never-push-default-branch"));

    let binary_dir = Path::new(env!("CARGO_BIN_EXE_base")).parent().unwrap();
    let resolved = base_with_path(
        project.path(),
        home.path(),
        binary_dir.as_os_str(),
        &["check", "--json"],
    );
    assert!(resolved.status.success());
    let report: serde_json::Value = serde_json::from_slice(&resolved.stdout).unwrap();
    assert_eq!(claude_denial(&report), "enforced");
    assert_eq!(report["warnings"], serde_json::json!([]));
}

#[test]
fn global_only_knowledge_stays_out_of_generated_output() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    success(project.path(), home.path(), &["sync"]);
    let baseline = fs::read_to_string(project.path().join("CLAUDE.md")).unwrap();

    fs::create_dir_all(home.path().join("canon/knowledge")).unwrap();
    fs::write(
        home.path().join("canon/knowledge/global-lesson.md"),
        "# Global lesson\n",
    )
    .unwrap();
    success(project.path(), home.path(), &["sync"]);
    success(project.path(), home.path(), &["sync", "--check"]);

    let with_global = fs::read_to_string(project.path().join("CLAUDE.md")).unwrap();
    assert_eq!(baseline, with_global);
    assert!(!with_global.contains("global-lesson"));

    let check = success(project.path(), home.path(), &["check", "--json"]);
    let report: serde_json::Value = serde_json::from_slice(&check.stdout).unwrap();
    assert!(
        report["warnings"]
            .as_array()
            .unwrap()
            .iter()
            .any(|warning| warning.as_str().unwrap().contains("global-lesson"))
    );
}

#[test]
fn global_only_definitions_stay_out_of_generated_output() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    success(project.path(), home.path(), &["sync"]);
    let baseline = fs::read_to_string(project.path().join("CLAUDE.md")).unwrap();

    fs::create_dir_all(home.path().join("canon/rules")).unwrap();
    fs::create_dir_all(home.path().join("canon/agents")).unwrap();
    fs::create_dir_all(home.path().join("canon/pipelines/stages")).unwrap();
    fs::write(
        home.path().join("canon/rules/no-force-push.md"),
        "---\nid: no-force-push\n---\n\nNever force-push shared branches.\n",
    )
    .unwrap();
    fs::write(
        home.path().join("canon/agents/researcher.md"),
        "---\nid: researcher\ndescription: Read-only exploration agent.\n---\n\nExplore; never edit.\n",
    )
    .unwrap();
    fs::write(
        home.path().join("canon/pipelines/stages/deploy.md"),
        "---\nid: deploy\n---\n\nShip the artifact.\n",
    )
    .unwrap();
    fs::write(
        home.path().join("canon/pipelines/ship.md"),
        "---\nid: ship\ndescription: Deploy and record.\nstages:\n  - use: deploy\n  - use: record\n---\n\nShip it.\n",
    )
    .unwrap();

    success(project.path(), home.path(), &["sync"]);
    success(project.path(), home.path(), &["sync", "--check"]);
    let with_global = fs::read_to_string(project.path().join("CLAUDE.md")).unwrap();
    assert_eq!(baseline, with_global);
    assert!(!project.path().join(".claude/agents/researcher.md").exists());
    assert!(!project.path().join(".claude/skills/ship").exists());
    assert!(
        !project
            .path()
            .join(".github/prompts/ship.prompt.md")
            .exists()
    );

    let check = success(project.path(), home.path(), &["check", "--json"]);
    let report: serde_json::Value = serde_json::from_slice(&check.stdout).unwrap();
    let warnings: Vec<String> = report["warnings"]
        .as_array()
        .unwrap()
        .iter()
        .map(|warning| warning.as_str().unwrap().to_owned())
        .collect();
    for needle in [
        "rule `no-force-push`",
        "agent `researcher`",
        "stage `deploy`",
        "pipeline `ship`",
    ] {
        assert!(
            warnings.iter().any(|warning| warning.contains(needle)),
            "missing warning for {needle}: {warnings:?}"
        );
    }
}

#[test]
fn project_pipeline_cannot_reference_global_only_stage() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    fs::create_dir_all(home.path().join("canon/pipelines/stages")).unwrap();
    fs::write(
        home.path().join("canon/pipelines/stages/deploy.md"),
        "---\nid: deploy\n---\n\nShip the artifact.\n",
    )
    .unwrap();
    fs::write(
        project.path().join(".base/canon/pipelines/ship.md"),
        "---\nid: ship\ndescription: Deploy and record.\nstages:\n  - use: deploy\n  - use: record\n---\n\nShip it.\n",
    )
    .unwrap();

    let failed = base(project.path(), home.path(), &["check"]);
    assert!(!failed.status.success());
    let stderr = String::from_utf8_lossy(&failed.stderr);
    assert!(stderr.contains("references global-only stage `deploy`"));
    assert!(stderr.contains("copy the stage into `.base/canon/pipelines/stages/`"));
}

#[test]
fn project_canon_overrides_global_canon_by_id() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--global"]);
    success(project.path(), home.path(), &["init", "--project"]);
    fs::write(
        home.path().join("canon/rules/working-agreements.md"),
        "---\nid: working-agreements\n---\n\nGLOBAL ONLY\n",
    )
    .unwrap();
    fs::write(
        project
            .path()
            .join(".base/canon/rules/working-agreements.md"),
        "---\nid: working-agreements\n---\n\nPROJECT WINS\n",
    )
    .unwrap();

    success(project.path(), home.path(), &["sync"]);
    let instructions = fs::read_to_string(project.path().join("AGENTS.md")).unwrap();
    assert!(instructions.contains("PROJECT WINS"));
    assert!(!instructions.contains("GLOBAL ONLY"));
}
