use std::ffi::OsStr;
use std::fs;
use std::io::Write;
use std::path::Path;
use std::process::{Command, Output, Stdio};

use tempfile::TempDir;

fn base(directory: &Path, home: &Path, arguments: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_base"))
        .arg("--directory")
        .arg(directory)
        .args(arguments)
        .env("BASE_HOME", home)
        .output()
        .expect("base command runs")
}

fn base_with_path(directory: &Path, home: &Path, path: &OsStr, arguments: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_base"))
        .arg("--directory")
        .arg(directory)
        .args(arguments)
        .env("BASE_HOME", home)
        .env("PATH", path)
        .output()
        .expect("base command runs")
}

fn success(directory: &Path, home: &Path, arguments: &[&str]) -> Output {
    let output = base(directory, home, arguments);
    assert!(
        output.status.success(),
        "base {arguments:?} failed:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr)
    );
    output
}

#[test]
fn walking_skeleton_syncs_and_detects_drift() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();

    success(project.path(), home.path(), &["init", "--project"]);
    success(project.path(), home.path(), &["check"]);
    success(project.path(), home.path(), &["sync"]);
    success(project.path(), home.path(), &["sync", "--check"]);

    assert!(project.path().join("CLAUDE.md").is_file());
    assert!(project.path().join("AGENTS.md").is_file());
    assert!(
        project
            .path()
            .join(".github/prompts/build.prompt.md")
            .is_file()
    );
    let codex_skill =
        fs::read_to_string(project.path().join(".agents/skills/build/SKILL.md")).unwrap();
    assert!(codex_skill.starts_with("---\n"));
    assert!(codex_skill.contains("generated by base sync"));
    let claude_settings = fs::read_to_string(project.path().join(".claude/settings.json")).unwrap();
    let settings: serde_json::Value = serde_json::from_str(&claude_settings).unwrap();
    assert!(settings.get("hooks").is_some());
    let matchers: Vec<&str> = settings["hooks"]["PreToolUse"]
        .as_array()
        .unwrap()
        .iter()
        .filter_map(|entry| entry["matcher"].as_str())
        .collect();
    assert!(matchers.contains(&"^(?:Bash)$"));
    assert!(matchers.contains(&"^(?:mcp__github__.*)$"));
    assert!(settings.get("_base_generated").is_none());
    assert!(
        project
            .path()
            .join(".agents/skills/build/SKILL.md")
            .is_file()
    );
    assert!(project.path().join(".codex/hooks.json").is_file());
    let codex_hooks: serde_json::Value = serde_json::from_str(
        &fs::read_to_string(project.path().join(".codex/hooks.json")).unwrap(),
    )
    .unwrap();
    assert!(codex_hooks["hooks"]["PreToolUse"].is_array());
    let shared_pipeline =
        fs::read_to_string(project.path().join(".agents/skills/build/SKILL.md")).unwrap();
    assert!(shared_pipeline.contains("actual runtime, `codex` or `copilot`"));
    assert!(!shared_pipeline.contains("Record `harness` as `codex`"));
    let copilot_hooks: serde_json::Value = serde_json::from_str(
        &fs::read_to_string(project.path().join(".github/hooks/base.json")).unwrap(),
    )
    .unwrap();
    assert!(
        copilot_hooks["hooks"]["PreToolUse"]
            .as_array()
            .unwrap()
            .iter()
            .any(|entry| entry["matcher"] == "^(?:github-mcp-server-.*)$")
    );

    fs::write(project.path().join("CLAUDE.md"), "hand edit\n").unwrap();
    let drift = base(project.path(), home.path(), &["sync", "--check", "--json"]);
    assert!(!drift.status.success());
    let error: serde_json::Value = serde_json::from_slice(&drift.stderr).unwrap();
    assert_eq!(error["ok"], false);
    assert!(error["error"].as_str().unwrap().contains("out of sync"));
    assert!(
        !base(project.path(), home.path(), &["sync"])
            .status
            .success()
    );
    success(project.path(), home.path(), &["sync", "--force"]);
    success(project.path(), home.path(), &["sync", "--check"]);
}

#[test]
fn sync_treats_crlf_checkout_conversion_as_equivalent_text() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    success(project.path(), home.path(), &["sync"]);

    let agents = project.path().join("AGENTS.md");
    let lf = fs::read_to_string(&agents).unwrap();
    assert!(!lf.contains("\r\n"));
    fs::write(&agents, lf.replace('\n', "\r\n")).unwrap();

    success(project.path(), home.path(), &["sync", "--check"]);
    let changed = fs::read_to_string(&agents).unwrap().replace(
        "Canonical definitions compile into this file",
        "Changed canonical definitions",
    );
    fs::write(&agents, changed).unwrap();
    let drift = base(project.path(), home.path(), &["sync", "--check"]);
    assert!(!drift.status.success());
    assert!(String::from_utf8_lossy(&drift.stderr).contains("content differs AGENTS.md"));
}

#[test]
fn init_preserves_config_and_history() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    success(project.path(), home.path(), &["sync"]);
    let config_before = fs::read_to_string(project.path().join(".base/base.toml")).unwrap();
    fs::write(
        project.path().join(".base/history.jsonl"),
        "{\"slug\":\"existing\"}\n",
    )
    .unwrap();

    success(project.path(), home.path(), &["init", "--project"]);

    assert_eq!(
        fs::read_to_string(project.path().join(".base/base.toml")).unwrap(),
        config_before
    );
    assert_eq!(
        fs::read_to_string(project.path().join(".base/history.jsonl")).unwrap(),
        "{\"slug\":\"existing\"}\n"
    );
}

#[test]
fn native_overlays_preserve_existing_harness_configuration() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    fs::create_dir_all(project.path().join(".base/native/.claude")).unwrap();
    fs::create_dir_all(project.path().join(".base/native/.codex")).unwrap();
    fs::write(
        project.path().join(".base/native/CLAUDE.md"),
        "# Existing Claude guidance\n\nKeep the legacy build command.\n",
    )
    .unwrap();
    fs::write(
        project.path().join(".base/native/.claude/settings.json"),
        r#"{"permissions":{"allow":["Bash(pnpm test)"]},"hooks":{"SessionStart":[{"hooks":[{"type":"command","command":"legacy-context"}]}]}}"#,
    )
    .unwrap();
    fs::write(
        project.path().join(".base/native/.codex/hooks.json"),
        r#"{"hooks":{"SessionStart":[{"hooks":[{"type":"command","command":"legacy-context"}]}]}}"#,
    )
    .unwrap();

    success(project.path(), home.path(), &["sync"]);
    success(project.path(), home.path(), &["sync", "--check"]);
    let claude = fs::read_to_string(project.path().join("CLAUDE.md")).unwrap();
    assert!(claude.contains("Existing Claude guidance"));
    assert!(claude.contains("project native supplement"));
    let settings: serde_json::Value = serde_json::from_str(
        &fs::read_to_string(project.path().join(".claude/settings.json")).unwrap(),
    )
    .unwrap();
    assert_eq!(settings["permissions"]["allow"][0], "Bash(pnpm test)");
    assert!(settings["permissions"]["deny"].is_array());
    assert!(settings["hooks"]["SessionStart"].is_array());
    assert!(settings["hooks"]["PreToolUse"].is_array());
    let codex: serde_json::Value = serde_json::from_str(
        &fs::read_to_string(project.path().join(".codex/hooks.json")).unwrap(),
    )
    .unwrap();
    assert!(codex["hooks"]["SessionStart"].is_array());
    assert!(codex["hooks"]["PreToolUse"].is_array());
}

#[test]
fn native_overlays_cannot_disable_base_owned_hooks() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    let overlay = project.path().join(".base/native/.github/hooks");
    fs::create_dir_all(&overlay).unwrap();
    fs::write(overlay.join("base.json"), r#"{"disableAllHooks":true}"#).unwrap();

    let output = base(project.path(), home.path(), &["sync"]);
    assert!(!output.status.success());
    assert!(String::from_utf8_lossy(&output.stderr).contains("cannot disable Base-owned hooks"));
    assert!(!project.path().join(".github/hooks/base.json").exists());
}

#[test]
fn removing_a_gate_removes_its_generated_bindings() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    success(project.path(), home.path(), &["sync"]);
    assert!(project.path().join(".claude/settings.json").is_file());
    assert!(project.path().join(".codex/rules/base.rules").is_file());

    let mut config = base_cli::config::Config::load(project.path()).unwrap();
    config
        .gates
        .retain(|gate| gate.id != "never-push-default-branch");
    config.save(project.path()).unwrap();
    success(project.path(), home.path(), &["sync"]);
    success(project.path(), home.path(), &["sync", "--check"]);

    // The artifact gate (default plan-approval) keeps its hooks, but the
    // removed standing denial takes its permission deny rules with it.
    let settings = fs::read_to_string(project.path().join(".claude/settings.json")).unwrap();
    assert!(!settings.contains("permissions"));
    assert!(settings.contains("Edit|Write|NotebookEdit"));
    assert!(!project.path().join(".codex/rules/base.rules").exists());
    assert!(project.path().join("CLAUDE.md").is_file());

    // A prose-only plan-approval (no artifact) leaves nothing to hook at all.
    let mut config = base_cli::config::Config::load(project.path()).unwrap();
    for gate in &mut config.gates {
        gate.satisfied_by = None;
    }
    config.save(project.path()).unwrap();
    success(project.path(), home.path(), &["sync"]);
    success(project.path(), home.path(), &["sync", "--check"]);
    assert!(!project.path().join(".claude/settings.json").exists());
}

#[test]
fn work_new_scaffolds_folder_item() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    let created = success(
        project.path(),
        home.path(),
        &[
            "work",
            "new",
            "Ship a useful thing",
            "--tags",
            "v1,test",
            "--criterion",
            "The CLI ships",
            "--criterion",
            " Tests pass ",
            "--json",
        ],
    );
    let created: serde_json::Value = serde_json::from_slice(&created.stdout).unwrap();
    assert_eq!(created["id"], "W-0001");
    assert_eq!(created["status"], "todo");
    assert_eq!(created["verdict"], "pending");
    assert_eq!(created["files"], serde_json::json!([]));
    assert_eq!(created["reservation_path"], ".base/work/.ids/W-0001");

    let item = project
        .path()
        .join(".base/work/W-0001-ship-a-useful-thing/item.md");
    assert!(item.is_file());
    assert_eq!(
        fs::read_to_string(project.path().join(".base/work/.ids/W-0001")).unwrap(),
        "W-0001-ship-a-useful-thing\n"
    );
    let raw = fs::read_to_string(item).unwrap();
    assert!(raw.contains("status: todo"));
    assert!(raw.contains("verdict: pending"));
    assert!(raw.contains("## Acceptance Criteria"));
    assert!(raw.contains("- [ ] The CLI ships"));
    assert!(raw.contains("- [ ] Tests pass"));

    let shown = success(
        project.path(),
        home.path(),
        &["work", "show", "W-0001", "--json"],
    );
    let value: serde_json::Value = serde_json::from_slice(&shown.stdout).unwrap();
    assert_eq!(value["title"], "Ship a useful thing");
    assert_eq!(value["tags"], serde_json::json!(["v1", "test"]));
    assert_eq!(value["body"], created["body"]);
}

#[test]
fn concurrent_work_creation_reserves_distinct_team_ids() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);

    let spawn = |title: &str| {
        Command::new(env!("CARGO_BIN_EXE_base"))
            .args([
                "--directory",
                project.path().to_str().unwrap(),
                "--json",
                "work",
                "new",
                title,
                "--criterion",
                "Reserved",
            ])
            .env("BASE_HOME", home.path())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .unwrap()
    };
    let first = spawn("Concurrent alpha");
    let second = spawn("Concurrent beta");
    let first = first.wait_with_output().unwrap();
    let second = second.wait_with_output().unwrap();
    assert!(
        first.status.success(),
        "{}",
        String::from_utf8_lossy(&first.stderr)
    );
    assert!(
        second.status.success(),
        "{}",
        String::from_utf8_lossy(&second.stderr)
    );
    let first: serde_json::Value = serde_json::from_slice(&first.stdout).unwrap();
    let second: serde_json::Value = serde_json::from_slice(&second.stdout).unwrap();
    assert_ne!(first["id"], second["id"]);
    assert!(project.path().join(".base/work/.ids/W-0001").is_file());
    assert!(project.path().join(".base/work/.ids/W-0002").is_file());
}

#[test]
fn duplicate_work_metadata_ids_fail_work_and_project_checks() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    success(
        project.path(),
        home.path(),
        &["work", "new", "First", "--criterion", "Unique"],
    );
    let duplicate = project.path().join(".base/work/W-0001-zduplicate");
    fs::create_dir(&duplicate).unwrap();
    fs::write(
        duplicate.join("item.md"),
        "---\nid: W-0001\ntitle: Duplicate\nstatus: todo\nverdict: pending\ncreated: 2026-07-20\ntags: []\n---\n\n# Duplicate\n\n## Acceptance Criteria\n\n- [ ] Rejected\n",
    )
    .unwrap();

    for arguments in [&["work", "list"][..], &["check"][..]] {
        let output = base(project.path(), home.path(), arguments);
        assert!(!output.status.success());
        assert!(
            String::from_utf8_lossy(&output.stderr).contains("duplicate work-item ID `W-0001`")
        );
    }
}

#[test]
fn invalid_retained_work_status_verdict_pairs_fail_project_checks() {
    for (status, verdict, expected) in [
        ("done", "pending", "status done requires verdict pass|fail"),
        (
            "todo",
            "pass",
            "status todo must have verdict pending; pass|fail only applies to done",
        ),
        (
            "doing",
            "fail",
            "status doing must have verdict pending; pass|fail only applies to done",
        ),
        (
            "review",
            "pass",
            "status review must have verdict pending; pass|fail only applies to done",
        ),
    ] {
        let project = TempDir::new().unwrap();
        let home = TempDir::new().unwrap();
        success(project.path(), home.path(), &["init", "--project"]);
        let item = project.path().join(".base/work/W-0001-invalid-state");
        fs::create_dir(&item).unwrap();
        fs::write(
            item.join("item.md"),
            format!(
                "---\nid: W-0001\ntitle: Invalid state\nstatus: {status}\nverdict: {verdict}\ncreated: 2026-07-20\ntags: []\n---\n\n# Invalid state\n\n## Acceptance Criteria\n\n- [ ] Rejected\n"
            ),
        )
        .unwrap();

        for arguments in [&["work", "list"][..], &["check"][..]] {
            let output = base(project.path(), home.path(), arguments);
            assert!(!output.status.success());
            assert!(
                String::from_utf8_lossy(&output.stderr).contains(expected),
                "{}",
                String::from_utf8_lossy(&output.stderr)
            );
        }
    }
}

#[test]
fn work_move_transitions_and_verdict_rules() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    success(
        project.path(),
        home.path(),
        &["work", "new", "Transition item", "--criterion", "Ready"],
    );
    success(
        project.path(),
        home.path(),
        &["work", "move", "W-0001", "doing"],
    );

    let missing_verdict = base(
        project.path(),
        home.path(),
        &["work", "move", "W-0001", "done"],
    );
    assert!(!missing_verdict.status.success());
    assert!(
        String::from_utf8_lossy(&missing_verdict.stderr)
            .contains("moving W-0001 to done requires --verdict pass|fail")
    );

    success(
        project.path(),
        home.path(),
        &["work", "move", "W-0001", "done", "--verdict", "pass"],
    );
    let reviewed = success(
        project.path(),
        home.path(),
        &["work", "move", "W-0001", "review", "--json"],
    );
    let reviewed: serde_json::Value = serde_json::from_slice(&reviewed.stdout).unwrap();
    assert_eq!(reviewed["status"], "review");
    assert_eq!(reviewed["verdict"], "pending");

    let misplaced_verdict = base(
        project.path(),
        home.path(),
        &["work", "move", "W-0001", "review", "--verdict", "pass"],
    );
    assert!(!misplaced_verdict.status.success());
    assert!(
        String::from_utf8_lossy(&misplaced_verdict.stderr)
            .contains("--verdict only applies when moving to done")
    );
}

#[test]
fn work_move_requires_acceptance_criteria() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    success(
        project.path(),
        home.path(),
        &["work", "new", "Criteria gate"],
    );

    let empty = base(
        project.path(),
        home.path(),
        &["work", "move", "W-0001", "doing"],
    );
    assert!(!empty.status.success());
    assert!(String::from_utf8_lossy(&empty.stderr).contains("W-0001 has no acceptance criteria"));

    let item = project
        .path()
        .join(".base/work/W-0001-criteria-gate/item.md");
    let source = fs::read_to_string(&item)
        .unwrap()
        .replace("## Acceptance Criteria", "## Notes");
    fs::write(item, source).unwrap();
    let missing = base(
        project.path(),
        home.path(),
        &["work", "move", "W-0001", "doing"],
    );
    assert!(!missing.status.success());
    assert!(
        String::from_utf8_lossy(&missing.stderr)
            .contains("W-0001 is missing its ## Acceptance Criteria section")
    );
}

#[test]
fn work_board_renders_columns() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    success(
        project.path(),
        home.path(),
        &["work", "new", "Todo card", "--criterion", "Queued"],
    );
    success(
        project.path(),
        home.path(),
        &["work", "new", "Done card", "--criterion", "Shipped"],
    );
    let done_item = project.path().join(".base/work/W-0002-done-card/item.md");
    let source = fs::read_to_string(&done_item)
        .unwrap()
        .replace("- [ ] Shipped", "- [x] Shipped");
    fs::write(done_item, source).unwrap();
    success(
        project.path(),
        home.path(),
        &["work", "move", "W-0002", "done", "--verdict", "pass"],
    );

    let rendered = success(project.path(), home.path(), &["work", "board"]);
    let rendered = String::from_utf8(rendered.stdout).unwrap();
    assert!(rendered.contains("TODO (1)"));
    assert!(rendered.contains("REVIEW (0)"));
    assert!(rendered.contains("W-0002 ✓"));

    let json = success(project.path(), home.path(), &["work", "board", "--json"]);
    let json: serde_json::Value = serde_json::from_slice(&json.stdout).unwrap();
    assert_eq!(json["todo"].as_array().unwrap().len(), 1);
    assert_eq!(json["doing"], serde_json::json!([]));
    assert_eq!(json["review"], serde_json::json!([]));
    assert_eq!(json["done"][0]["verdict"], "pass");
}

#[test]
fn work_list_validates_status_filter() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    success(
        project.path(),
        home.path(),
        &["work", "new", "Doing item", "--criterion", "Started"],
    );
    success(
        project.path(),
        home.path(),
        &["work", "move", "W-0001", "doing"],
    );
    success(
        project.path(),
        home.path(),
        &["work", "new", "Todo item", "--criterion", "Queued"],
    );

    let filtered = success(
        project.path(),
        home.path(),
        &["work", "list", "--status", "doing", "--json"],
    );
    let filtered: serde_json::Value = serde_json::from_slice(&filtered.stdout).unwrap();
    assert_eq!(filtered.as_array().unwrap().len(), 1);
    assert_eq!(filtered[0]["id"], "W-0001");

    let invalid = base(
        project.path(),
        home.path(),
        &["work", "list", "--status", "open"],
    );
    assert!(!invalid.status.success());
    let stderr = String::from_utf8_lossy(&invalid.stderr);
    assert!(stderr.contains("possible values"));
    assert!(stderr.contains("todo"));
    assert!(stderr.contains("doing"));
    assert!(stderr.contains("review"));
    assert!(stderr.contains("done"));
}

#[test]
fn work_ignores_attachments_and_strays() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    success(
        project.path(),
        home.path(),
        &["work", "new", "Attached item", "--criterion", "Documented"],
    );
    let work = project.path().join(".base/work");
    let item = work.join("W-0001-attached-item");
    fs::create_dir_all(item.join("attachments")).unwrap();
    fs::write(item.join("attachments/data.txt"), "data\n").unwrap();
    fs::write(item.join("notes.md"), "notes\n").unwrap();
    fs::write(work.join("random.md"), "legacy\n").unwrap();
    fs::create_dir(work.join("W-0009-empty")).unwrap();

    let listed = base(project.path(), home.path(), &["work", "list", "--json"]);
    assert!(listed.status.success());
    let listed_json: serde_json::Value = serde_json::from_slice(&listed.stdout).unwrap();
    assert_eq!(listed_json.as_array().unwrap().len(), 1);
    assert_eq!(
        listed_json[0]["files"],
        serde_json::json!([
            ".base/work/W-0001-attached-item/attachments/data.txt",
            ".base/work/W-0001-attached-item/notes.md"
        ])
    );
    let stderr = String::from_utf8_lossy(&listed.stderr);
    assert!(stderr.contains("warning: ignoring legacy work file .base/work/random.md"));
    assert!(
        stderr.contains("warning: ignoring work directory without item.md .base/work/W-0009-empty")
    );
}

#[test]
fn work_new_sequences_ids_past_stray_folders() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    fs::create_dir(project.path().join(".base/work/W-0007-ghost")).unwrap();

    let created = success(
        project.path(),
        home.path(),
        &[
            "work",
            "new",
            "Next item",
            "--criterion",
            "Sequenced",
            "--json",
        ],
    );
    let created: serde_json::Value = serde_json::from_slice(&created.stdout).unwrap();
    assert_eq!(created["id"], "W-0008");
    assert!(
        project
            .path()
            .join(".base/work/W-0008-next-item/item.md")
            .is_file()
    );
}

#[test]
fn log_reads_aborted_runs() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    let run = project.path().join(".base/runs/2026-07-14-aborted-example");
    fs::create_dir_all(&run).unwrap();
    fs::write(run.join("task.md"), "# Aborted example\n").unwrap();
    fs::write(
        project.path().join(".base/history.jsonl"),
        "{\"slug\":\"2026-07-14-aborted-example\",\"date\":\"2026-07-14\",\"pipeline\":\"build\",\"harness\":\"codex\",\"outcome\":\"aborted\",\"paths\":[\".base/runs/2026-07-14-aborted-example/task.md\"]}\n",
    )
    .unwrap();

    let listed = success(project.path(), home.path(), &["log", "--json"]);
    let history: serde_json::Value = serde_json::from_slice(&listed.stdout).unwrap();
    assert_eq!(history[0]["outcome"], "aborted");
    let shown = success(
        project.path(),
        home.path(),
        &["log", "2026-07-14-aborted-example", "--json"],
    );
    let report: serde_json::Value = serde_json::from_slice(&shown.stdout).unwrap();
    assert_eq!(report["history"][0]["outcome"], "aborted");
    assert_eq!(
        report["files"][0],
        ".base/runs/2026-07-14-aborted-example/task.md"
    );
}

#[test]
fn check_downgrades_claude_hook_enforcement_when_base_is_off_path() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);

    let claude_denial = |report: &serde_json::Value| {
        report["enforcement"]
            .as_array()
            .unwrap()
            .iter()
            .find(|row| row["gate"] == "never-push-default-branch" && row["target"] == "claude")
            .expect("claude standing-denial row exists")["fidelity"]
            .clone()
    };

    let empty_dir = TempDir::new().unwrap();
    let missing = base_with_path(
        project.path(),
        home.path(),
        empty_dir.path().as_os_str(),
        &["check", "--json"],
    );
    assert!(missing.status.success());
    let report: serde_json::Value = serde_json::from_slice(&missing.stdout).unwrap();
    assert_eq!(claude_denial(&report), "assisted");
    // Both enforced cells (artifact plan-approval + standing denial) downgrade
    // with their own warnings when the hook binary cannot run.
    let warnings: Vec<&str> = report["warnings"]
        .as_array()
        .unwrap()
        .iter()
        .filter_map(|warning| warning.as_str())
        .collect();
    assert!(warnings.iter().all(|warning| warning.contains("PATH")));
    assert!(
        warnings
            .iter()
            .any(|warning| warning.contains("never-push-default-branch"))
    );
    assert!(
        warnings
            .iter()
            .any(|warning| warning.contains("plan-approval"))
    );

    let binary_dir = Path::new(env!("CARGO_BIN_EXE_base")).parent().unwrap();
    let resolved = base_with_path(
        project.path(),
        home.path(),
        binary_dir.as_os_str(),
        &["check", "--json"],
    );
    assert!(resolved.status.success());
    let report: serde_json::Value = serde_json::from_slice(&resolved.stdout).unwrap();
    assert_eq!(claude_denial(&report), "native-hook");
    assert_eq!(report["warnings"], serde_json::json!([]));
}

#[test]
fn approve_writes_a_create_new_stamped_verdict() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    let demo_approvals = project.path().join(".base/runs/2026-07-15-demo/approvals");
    fs::create_dir_all(&demo_approvals).unwrap();
    fs::write(
        demo_approvals.join("plan-approval.md.request"),
        "Review the plan.",
    )
    .unwrap();

    let approved = success(
        project.path(),
        home.path(),
        &[
            "approve",
            "2026-07-15-demo",
            "plan-approval",
            "--by",
            "tester",
            "--note",
            "standing: session goal directive",
            "--json",
        ],
    );
    let report: serde_json::Value = serde_json::from_slice(&approved.stdout).unwrap();
    assert_eq!(report["verdict"], "approved");
    assert_eq!(report["by"], "tester");

    let artifact = project
        .path()
        .join(".base/runs/2026-07-15-demo/approvals/plan-approval.md");
    let record = fs::read_to_string(&artifact).unwrap();
    assert!(record.contains("verdict: approved"));
    assert!(record.contains("by: tester"));
    assert!(record.contains("note: standing: session goal directive"));

    // Verdicts are immutable; unknown gates and runs are refused.
    let duplicate = base(
        project.path(),
        home.path(),
        &["approve", "2026-07-15-demo", "plan-approval"],
    );
    assert!(!duplicate.status.success());
    assert!(
        String::from_utf8_lossy(&duplicate.stderr).contains("already exists"),
        "duplicate verdict is refused"
    );
    let unknown_gate = base(
        project.path(),
        home.path(),
        &["approve", "2026-07-15-demo", "no-such-gate"],
    );
    assert!(!unknown_gate.status.success());
    let unknown_run = base(
        project.path(),
        home.path(),
        &["approve", "no-such-run", "plan-approval", "--deny"],
    );
    assert!(!unknown_run.status.success());

    // A denial is a first-class verdict on a fresh run.
    let denied_approvals = project
        .path()
        .join(".base/runs/2026-07-15-denied/approvals");
    fs::create_dir_all(&denied_approvals).unwrap();
    fs::write(
        denied_approvals.join("plan-approval.md.request"),
        "Review the plan.",
    )
    .unwrap();
    let denied = success(
        project.path(),
        home.path(),
        &[
            "approve",
            "2026-07-15-denied",
            "plan-approval",
            "--deny",
            "--json",
        ],
    );
    let report: serde_json::Value = serde_json::from_slice(&denied.stdout).unwrap();
    assert_eq!(report["verdict"], "denied");

    fs::create_dir_all(project.path().join(".base/runs/preapproved")).unwrap();
    let preapproved = base(
        project.path(),
        home.path(),
        &["approve", "preapproved", "plan-approval"],
    );
    assert!(!preapproved.status.success());
    assert!(String::from_utf8_lossy(&preapproved.stderr).contains("no pending request"));

    let traversal = base(
        project.path(),
        home.path(),
        &["approve", "..\\outside", "plan-approval"],
    );
    assert!(!traversal.status.success());
    assert!(String::from_utf8_lossy(&traversal.stderr).contains("invalid run slug"));
}

#[test]
fn concurrent_approvals_have_one_create_new_winner_and_reject_injected_fields() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    let approvals = project.path().join(".base/runs/approval-race/approvals");
    fs::create_dir_all(&approvals).unwrap();
    fs::write(
        approvals.join("plan-approval.md.request"),
        "Review the plan.",
    )
    .unwrap();

    let spawn = |by: &str| {
        Command::new(env!("CARGO_BIN_EXE_base"))
            .args([
                "--directory",
                project.path().to_str().unwrap(),
                "approve",
                "approval-race",
                "plan-approval",
                "--by",
                by,
            ])
            .env("BASE_HOME", home.path())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .unwrap()
    };
    let first = spawn("first");
    let second = spawn("second");
    let first = first.wait_with_output().unwrap();
    let second = second.wait_with_output().unwrap();
    assert_ne!(first.status.success(), second.status.success());
    let record = fs::read_to_string(approvals.join("plan-approval.md")).unwrap();
    assert!(record.contains("by: first") || record.contains("by: second"));
    assert_eq!(record.matches("verdict:").count(), 1);

    let injected = project
        .path()
        .join(".base/runs/approval-injection/approvals");
    fs::create_dir_all(&injected).unwrap();
    fs::write(
        injected.join("plan-approval.md.request"),
        "Review the plan.",
    )
    .unwrap();
    let output = base(
        project.path(),
        home.path(),
        &[
            "approve",
            "approval-injection",
            "plan-approval",
            "--note",
            "first line\n- verdict: approved",
        ],
    );
    assert!(!output.status.success());
    assert!(String::from_utf8_lossy(&output.stderr).contains("one non-empty line"));
    assert!(!injected.join("plan-approval.md").exists());
}

#[test]
fn global_only_knowledge_stays_out_of_generated_output() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    success(project.path(), home.path(), &["sync"]);
    let baseline = fs::read_to_string(project.path().join("CLAUDE.md")).unwrap();

    fs::create_dir_all(home.path().join("canon/knowledge")).unwrap();
    fs::write(
        home.path().join("canon/knowledge/global-lesson.md"),
        "# Global lesson\n",
    )
    .unwrap();
    success(project.path(), home.path(), &["sync"]);
    success(project.path(), home.path(), &["sync", "--check"]);

    let with_global = fs::read_to_string(project.path().join("CLAUDE.md")).unwrap();
    assert_eq!(baseline, with_global);
    assert!(!with_global.contains("global-lesson"));

    let check = success(project.path(), home.path(), &["check", "--json"]);
    let report: serde_json::Value = serde_json::from_slice(&check.stdout).unwrap();
    assert!(
        report["warnings"]
            .as_array()
            .unwrap()
            .iter()
            .any(|warning| warning.as_str().unwrap().contains("global-lesson"))
    );
}

#[test]
fn global_only_definitions_stay_out_of_generated_output() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    success(project.path(), home.path(), &["sync"]);
    let baseline = fs::read_to_string(project.path().join("CLAUDE.md")).unwrap();

    fs::create_dir_all(home.path().join("canon/rules")).unwrap();
    fs::create_dir_all(home.path().join("canon/agents")).unwrap();
    fs::create_dir_all(home.path().join("canon/pipelines/stages")).unwrap();
    fs::write(
        home.path().join("canon/rules/no-force-push.md"),
        "---\nid: no-force-push\n---\n\nNever force-push shared branches.\n",
    )
    .unwrap();
    fs::write(
        home.path().join("canon/agents/researcher.md"),
        "---\nid: researcher\ndescription: Read-only exploration agent.\n---\n\nExplore; never edit.\n",
    )
    .unwrap();
    fs::write(
        home.path().join("canon/pipelines/stages/deploy.md"),
        "---\nid: deploy\n---\n\nShip the artifact.\n",
    )
    .unwrap();
    fs::write(
        home.path().join("canon/pipelines/ship.md"),
        "---\nid: ship\ndescription: Deploy and record.\nstages:\n  - use: deploy\n  - use: record\n---\n\nShip it.\n",
    )
    .unwrap();

    success(project.path(), home.path(), &["sync"]);
    success(project.path(), home.path(), &["sync", "--check"]);
    let with_global = fs::read_to_string(project.path().join("CLAUDE.md")).unwrap();
    assert_eq!(baseline, with_global);
    assert!(!project.path().join(".claude/agents/researcher.md").exists());
    assert!(!project.path().join(".claude/skills/ship").exists());
    assert!(
        !project
            .path()
            .join(".github/prompts/ship.prompt.md")
            .exists()
    );

    let check = success(project.path(), home.path(), &["check", "--json"]);
    let report: serde_json::Value = serde_json::from_slice(&check.stdout).unwrap();
    let warnings: Vec<String> = report["warnings"]
        .as_array()
        .unwrap()
        .iter()
        .map(|warning| warning.as_str().unwrap().to_owned())
        .collect();
    for needle in [
        "rule `no-force-push`",
        "agent `researcher`",
        "stage `deploy`",
        "pipeline `ship`",
    ] {
        assert!(
            warnings.iter().any(|warning| warning.contains(needle)),
            "missing warning for {needle}: {warnings:?}"
        );
    }
}

#[test]
fn project_pipeline_cannot_reference_global_only_stage() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    fs::create_dir_all(home.path().join("canon/pipelines/stages")).unwrap();
    fs::write(
        home.path().join("canon/pipelines/stages/deploy.md"),
        "---\nid: deploy\n---\n\nShip the artifact.\n",
    )
    .unwrap();
    fs::write(
        project.path().join(".base/canon/pipelines/ship.md"),
        "---\nid: ship\ndescription: Deploy and record.\nstages:\n  - use: deploy\n  - use: record\n---\n\nShip it.\n",
    )
    .unwrap();

    let failed = base(project.path(), home.path(), &["check"]);
    assert!(!failed.status.success());
    let stderr = String::from_utf8_lossy(&failed.stderr);
    assert!(stderr.contains("references global-only stage `deploy`"));
    assert!(stderr.contains("copy the stage into `.base/canon/pipelines/stages/`"));
}

#[test]
fn project_canon_overrides_global_canon_by_id() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--global"]);
    success(project.path(), home.path(), &["init", "--project"]);
    fs::write(
        home.path().join("canon/rules/working-agreements.md"),
        "---\nid: working-agreements\n---\n\nGLOBAL ONLY\n",
    )
    .unwrap();
    fs::write(
        project
            .path()
            .join(".base/canon/rules/working-agreements.md"),
        "---\nid: working-agreements\n---\n\nPROJECT WINS\n",
    )
    .unwrap();

    success(project.path(), home.path(), &["sync"]);
    let instructions = fs::read_to_string(project.path().join("AGENTS.md")).unwrap();
    assert!(instructions.contains("PROJECT WINS"));
    assert!(!instructions.contains("GLOBAL ONLY"));
}

fn write_test_pack(home: &Path) {
    let pack = home.join("canon/packs/testpack");
    fs::create_dir_all(pack.join("rules")).unwrap();
    fs::create_dir_all(pack.join("knowledge")).unwrap();
    fs::write(
        pack.join("pack.md"),
        "---\nid: testpack\nversion: 1.0.0\ndescription: Test pack.\n---\n\nManifest.\n",
    )
    .unwrap();
    fs::write(
        pack.join("rules/testpack-rules.md"),
        "---\nid: testpack-rules\ndescription: Test rules.\n---\n\n- Be excellent.\n",
    )
    .unwrap();
    fs::write(
        pack.join("knowledge/testpack-notes.md"),
        "---\nid: testpack-notes\ndescription: Test notes.\n---\n\nNotes.\n",
    )
    .unwrap();
}

fn write_rule_pack(home: &Path, id: &str, rule_id: &str, body: &str) {
    let pack = home.join("canon/packs").join(id);
    fs::create_dir_all(pack.join("rules")).unwrap();
    fs::write(
        pack.join("pack.md"),
        format!("---\nid: {id}\nversion: 1.0.0\ndescription: {id} test pack.\n---\n\nManifest.\n"),
    )
    .unwrap();
    fs::write(
        pack.join("rules/shared.md"),
        format!("---\nid: {rule_id}\ndescription: Shared rule.\n---\n\n{body}\n"),
    )
    .unwrap();
}

#[test]
fn concurrent_pack_adoptions_preserve_both_config_updates() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    write_rule_pack(home.path(), "alpha", "alpha-rule", "ALPHA");
    write_rule_pack(home.path(), "beta", "beta-rule", "BETA");

    let spawn = |pack: &str| {
        Command::new(env!("CARGO_BIN_EXE_base"))
            .args([
                "--directory",
                project.path().to_str().unwrap(),
                "adopt",
                pack,
            ])
            .env("BASE_HOME", home.path())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .unwrap()
    };
    let alpha = spawn("alpha");
    let beta = spawn("beta");
    let alpha = alpha.wait_with_output().unwrap();
    let beta = beta.wait_with_output().unwrap();
    assert!(
        alpha.status.success(),
        "{}",
        String::from_utf8_lossy(&alpha.stderr)
    );
    assert!(
        beta.status.success(),
        "{}",
        String::from_utf8_lossy(&beta.stderr)
    );

    let config = base_cli::config::Config::load(project.path()).unwrap();
    let ids: Vec<&str> = config.packs.iter().map(|pack| pack.id.as_str()).collect();
    assert_eq!(ids.len(), 2);
    assert!(ids.contains(&"alpha"));
    assert!(ids.contains(&"beta"));
    success(project.path(), home.path(), &["sync"]);
    success(project.path(), home.path(), &["sync", "--check"]);
}

#[test]
fn global_init_installs_the_bundled_software_delivery_library_pack() {
    let directory = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(directory.path(), home.path(), &["init", "--global"]);
    let manifest =
        fs::read_to_string(home.path().join("canon/packs/software-delivery/pack.md")).unwrap();
    assert!(manifest.contains("id: software-delivery"));
    assert!(manifest.contains("version: 1.2.0"));
    assert!(
        home.path()
            .join("canon/packs/software-delivery/policies/session-context.md")
            .is_file()
    );
    fs::write(
        home.path().join("canon/packs/software-delivery/pack.md"),
        "locally stale\n",
    )
    .unwrap();
    fs::write(
        home.path().join("canon/rules/working-agreements.md"),
        "personal global agreements\n",
    )
    .unwrap();
    success(
        directory.path(),
        home.path(),
        &["init", "--global", "--packs-only", "--force"],
    );
    let restored =
        fs::read_to_string(home.path().join("canon/packs/software-delivery/pack.md")).unwrap();
    assert!(restored.contains("version: 1.2.0"));
    assert_eq!(
        fs::read_to_string(home.path().join("canon/rules/working-agreements.md")).unwrap(),
        "personal global agreements\n"
    );
}

#[test]
fn later_packs_win_and_the_project_overlay_wins_last() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    write_rule_pack(home.path(), "first", "shared-rule", "FIRST PACK");
    write_rule_pack(home.path(), "second", "shared-rule", "SECOND PACK");
    success(project.path(), home.path(), &["adopt", "first"]);
    success(project.path(), home.path(), &["adopt", "second"]);
    success(project.path(), home.path(), &["sync"]);
    let instructions = fs::read_to_string(project.path().join("AGENTS.md")).unwrap();
    assert!(instructions.contains("SECOND PACK"));
    assert!(!instructions.contains("FIRST PACK"));

    fs::write(
        project.path().join(".base/canon/rules/shared.md"),
        "---\nid: shared-rule\ndescription: Project rule.\n---\n\nPROJECT OVERLAY\n",
    )
    .unwrap();
    success(project.path(), home.path(), &["sync"]);
    let instructions = fs::read_to_string(project.path().join("AGENTS.md")).unwrap();
    assert!(instructions.contains("PROJECT OVERLAY"));
    assert!(!instructions.contains("SECOND PACK"));
    let checked = success(project.path(), home.path(), &["check", "--json"]);
    let report: serde_json::Value = serde_json::from_slice(&checked.stdout).unwrap();
    assert!(report["overrides"].as_array().unwrap().iter().any(|item| {
        item["id"] == "shared-rule"
            && item["replaced"] == "pack:second"
            && item["winner"] == "project"
    }));
}

#[test]
fn adopt_vendors_versioned_pack_and_composes_it() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    write_test_pack(home.path());

    let output = success(project.path(), home.path(), &["adopt", "testpack"]);
    let stdout = String::from_utf8_lossy(&output.stdout);

    assert!(
        project
            .path()
            .join(".base/packs/testpack/rules/testpack-rules.md")
            .is_file()
    );
    assert!(
        project
            .path()
            .join(".base/packs/testpack/knowledge/testpack-notes.md")
            .is_file()
    );
    assert!(project.path().join(".base/packs/testpack/pack.md").exists());
    assert!(stdout.contains("version 1.0.0"));
    assert!(stdout.contains("base sync"));
    assert!(stdout.contains("commit the pack"));

    let config = fs::read_to_string(project.path().join(".base/base.toml")).unwrap();
    assert!(config.contains("[[packs]]"));
    assert!(config.contains("version = \"1.0.0\""));

    success(project.path(), home.path(), &["sync"]);
    success(project.path(), home.path(), &["check"]);
}

#[test]
fn adopt_upgrade_requires_a_new_immutable_version() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    write_test_pack(home.path());
    success(project.path(), home.path(), &["adopt", "testpack"]);

    fs::write(
        home.path().join("canon/packs/testpack/rules/extra.md"),
        "---\nid: extra\ndescription: Added later.\n---\n\n- More.\n",
    )
    .unwrap();

    let failed = base(
        project.path(),
        home.path(),
        &["adopt", "testpack", "--upgrade"],
    );
    assert!(!failed.status.success());
    let stderr = String::from_utf8_lossy(&failed.stderr);
    assert!(stderr.contains("version 1.0.0 changed content"));
    assert!(
        !project
            .path()
            .join(".base/packs/testpack/rules/extra.md")
            .exists()
    );

    fs::write(
        home.path().join("canon/packs/testpack/pack.md"),
        "---\nid: testpack\nversion: 1.1.0\ndescription: Test pack.\n---\n\nManifest.\n",
    )
    .unwrap();
    success(
        project.path(),
        home.path(),
        &["adopt", "testpack", "--upgrade"],
    );
    assert!(
        project
            .path()
            .join(".base/packs/testpack/rules/extra.md")
            .exists()
    );
}

#[test]
fn adopt_unknown_pack_lists_available() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    write_test_pack(home.path());

    let failed = base(project.path(), home.path(), &["adopt", "nope"]);
    assert!(!failed.status.success());
    let stderr = String::from_utf8_lossy(&failed.stderr);
    assert!(stderr.contains("no pack `nope`"));
    assert!(stderr.contains("available packs: testpack"));
}

#[test]
fn adopt_requires_initialized_project() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    fs::create_dir(project.path().join(".git")).unwrap();
    write_test_pack(home.path());

    let failed = base(project.path(), home.path(), &["adopt", "testpack"]);
    assert!(!failed.status.success());
    let stderr = String::from_utf8_lossy(&failed.stderr);
    assert!(stderr.contains("base init"));
}

#[test]
fn installed_pack_drift_is_rejected_before_composition() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    write_test_pack(home.path());
    success(project.path(), home.path(), &["adopt", "testpack"]);
    fs::write(
        project
            .path()
            .join(".base/packs/testpack/rules/testpack-rules.md"),
        "local mutation\n",
    )
    .unwrap();

    let failed = base(project.path(), home.path(), &["check"]);
    assert!(!failed.status.success());
    let stderr = String::from_utf8_lossy(&failed.stderr);
    assert!(stderr.contains("modified locally"), "{stderr}");
    assert!(
        stderr.contains("changed rules/testpack-rules.md"),
        "{stderr}"
    );
}

#[test]
fn skills_agents_and_policies_compile_to_native_target_surfaces() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);

    let skill = project.path().join(".base/canon/skills/diagnostic");
    fs::create_dir_all(skill.join("references")).unwrap();
    fs::write(
        skill.join("SKILL.md"),
        "---\nid: diagnostic\ndescription: Diagnose a bounded repository problem.\n---\n\nUse the checklist.\n",
    )
    .unwrap();
    fs::write(skill.join("references/checklist.md"), "# Checklist\n").unwrap();
    fs::write(
        project.path().join(".base/canon/agents/specialist.md"),
        "---\nid: specialist\ndescription: Read-only diagnostic specialist.\naccess: read-only\nskills:\n  - diagnostic\n---\n\nFind the causal path.\n",
    )
    .unwrap();
    fs::create_dir_all(project.path().join(".base/canon/policies")).unwrap();
    fs::write(
        project
            .path()
            .join(".base/canon/policies/session-context.md"),
        "---\nid: session-context\ndescription: Load current Base state.\nevent: session-start\nmode: context\ncommand: [base, state, context]\n---\n\nLoad it manually when hooks are unavailable.\n",
    )
    .unwrap();

    success(project.path(), home.path(), &["sync"]);
    for path in [
        ".claude/skills/diagnostic/SKILL.md",
        ".claude/skills/diagnostic/references/checklist.md",
        ".agents/skills/diagnostic/SKILL.md",
        ".agents/skills/diagnostic/references/checklist.md",
        ".claude/agents/specialist.md",
        ".codex/agents/specialist.toml",
        ".github/agents/specialist.agent.md",
        ".github/hooks/base.json",
    ] {
        assert!(project.path().join(path).is_file(), "missing {path}");
    }
    let codex_agent =
        fs::read_to_string(project.path().join(".codex/agents/specialist.toml")).unwrap();
    assert!(codex_agent.contains("sandbox_mode = \"read-only\""));
    assert!(codex_agent.contains("$diagnostic"));
    let codex_agent_toml: toml::Value = toml::from_str(&codex_agent).unwrap();
    assert_eq!(codex_agent_toml["name"].as_str(), Some("specialist"));
    let claude_agent =
        fs::read_to_string(project.path().join(".claude/agents/specialist.md")).unwrap();
    assert!(claude_agent.contains("permissionMode: plan"));
    let copilot_agent =
        fs::read_to_string(project.path().join(".github/agents/specialist.agent.md")).unwrap();
    assert!(copilot_agent.contains("tools: [read, search]"));
    let (frontmatter, _) = base_cli::canon::split_frontmatter(&copilot_agent).unwrap();
    let copilot_agent_yaml: serde_yaml::Value = serde_yaml::from_str(frontmatter).unwrap();
    assert_eq!(
        copilot_agent_yaml["description"].as_str(),
        Some("Read-only diagnostic specialist.")
    );
    let claude_settings: serde_json::Value = serde_json::from_str(
        &fs::read_to_string(project.path().join(".claude/settings.json")).unwrap(),
    )
    .unwrap();
    assert!(claude_settings["hooks"]["SessionStart"].is_array());
    let copilot_hooks: serde_json::Value = serde_json::from_str(
        &fs::read_to_string(project.path().join(".github/hooks/base.json")).unwrap(),
    )
    .unwrap();
    assert_eq!(copilot_hooks["version"], 1);
    assert!(copilot_hooks["hooks"]["SessionStart"].is_array());
    success(project.path(), home.path(), &["sync", "--check"]);
}

#[test]
fn policy_tool_globs_preserve_capability_meaning_through_target_aliases() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    let policies = project.path().join(".base/canon/policies");
    fs::create_dir_all(&policies).unwrap();
    fs::write(
        policies.join("portable-match.md"),
        "---\nid: portable-match\ndescription: Match the same full tool names everywhere.\nevent: pre-tool-use\nmode: guard\ncommand: [rustc, --version]\nmatch-tools: [Edit, NotebookEdit, \"mcp__github__*\"]\n---\n\nPortable matcher.\n",
    )
    .unwrap();
    success(project.path(), home.path(), &["sync"]);

    for (path, expected) in [
        (
            ".claude/settings.json",
            "^(?:Edit|NotebookEdit|mcp__github__.*)$",
        ),
        (".codex/hooks.json", "^(?:apply_patch|mcp__github__.*)$"),
        (".github/hooks/base.json", "^(?:Edit|github-mcp-server-.*)$"),
    ] {
        let value: serde_json::Value =
            serde_json::from_str(&fs::read_to_string(project.path().join(path)).unwrap()).unwrap();
        let group = value["hooks"]["PreToolUse"]
            .as_array()
            .unwrap()
            .iter()
            .find(|group| group.to_string().contains("portable-match"))
            .unwrap_or_else(|| panic!("portable policy missing from {path}"));
        assert_eq!(group["matcher"], expected, "{path}");
    }
}

#[test]
fn lifecycle_policy_wrapper_translates_context_for_each_hook_protocol() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    fs::create_dir_all(project.path().join(".base/canon/policies")).unwrap();
    fs::write(
        project.path().join(".base/canon/policies/compiler.md"),
        "---\nid: compiler\ndescription: Report the Rust compiler.\nevent: session-start\nmode: context\ncommand: [rustc, --version]\n---\n\nCompiler context.\n",
    )
    .unwrap();

    for target in ["claude", "codex", "copilot"] {
        let mut child = Command::new(env!("CARGO_BIN_EXE_base"))
            .args([
                "--directory",
                project.path().to_str().unwrap(),
                "__hook",
                "policy",
                "compiler",
                "--target",
                target,
            ])
            .env("BASE_HOME", home.path())
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .unwrap();
        let event = format!(
            "{{\"cwd\":{}}}",
            serde_json::to_string(project.path()).unwrap()
        );
        child
            .stdin
            .take()
            .unwrap()
            .write_all(event.as_bytes())
            .unwrap();
        let output = child.wait_with_output().unwrap();
        assert!(
            output.status.success(),
            "{}",
            String::from_utf8_lossy(&output.stderr)
        );
        let result: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
        let context = if matches!(target, "claude" | "codex") {
            &result["hookSpecificOutput"]["additionalContext"]
        } else {
            &result["additionalContext"]
        };
        assert!(context.as_str().unwrap().starts_with("rustc "));
    }
}

#[test]
fn guard_policy_failure_posture_is_explicit() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    fs::create_dir_all(project.path().join(".base/canon/policies")).unwrap();
    for (id, fail_closed) in [("closed-guard", true), ("open-guard", false)] {
        fs::write(
            project
                .path()
                .join(format!(".base/canon/policies/{id}.md")),
            format!(
                "---\nid: {id}\ndescription: Missing guard command.\nevent: pre-tool-use\nmode: guard\ncommand: [definitely-missing-base-guard-program]\nfail-closed: {fail_closed}\n---\n\nGuard fallback.\n"
            ),
        )
        .unwrap();
    }

    for (id, denied) in [("closed-guard", true), ("open-guard", false)] {
        let mut child = Command::new(env!("CARGO_BIN_EXE_base"))
            .args([
                "--directory",
                project.path().to_str().unwrap(),
                "__hook",
                "policy",
                id,
                "--target",
                "copilot",
            ])
            .env("BASE_HOME", home.path())
            .stdin(Stdio::piped())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .unwrap();
        let event = format!(
            "{{\"cwd\":{},\"tool_name\":\"Bash\",\"tool_input\":{{}}}}",
            serde_json::to_string(project.path()).unwrap()
        );
        child
            .stdin
            .take()
            .unwrap()
            .write_all(event.as_bytes())
            .unwrap();
        let output = child.wait_with_output().unwrap();
        assert!(output.status.success());
        if denied {
            let decision: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
            assert_eq!(decision["permissionDecision"], "deny");
        } else {
            assert!(output.stdout.is_empty());
            assert!(String::from_utf8_lossy(&output.stderr).contains("base hook warning"));
        }
    }
}

#[cfg(windows)]
#[test]
fn policy_timeout_is_bounded_when_child_never_reads_large_stdin() {
    use std::time::{Duration, Instant};

    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    let policies = project.path().join(".base/canon/policies");
    fs::create_dir_all(&policies).unwrap();
    let command = serde_json::to_string(&vec![
        "powershell.exe",
        "-NoProfile",
        "-Command",
        "Start-Sleep -Seconds 10",
    ])
    .unwrap();
    fs::write(
        policies.join("non-reader.md"),
        format!(
            "---\nid: non-reader\ndescription: Non-reading timeout guard.\nevent: pre-tool-use\nmode: guard\ncommand: {command}\ntimeout-seconds: 1\nfail-closed: true\n---\n\nDeny on timeout.\n"
        ),
    )
    .unwrap();

    let mut child = Command::new(env!("CARGO_BIN_EXE_base"))
        .args([
            "--directory",
            project.path().to_str().unwrap(),
            "__hook",
            "policy",
            "non-reader",
            "--target",
            "copilot",
        ])
        .env("BASE_HOME", home.path())
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .unwrap();
    let event = serde_json::json!({
        "cwd": project.path(),
        "tool_name": "Bash",
        "tool_input": {},
        "padding": "x".repeat(512 * 1024)
    });
    let started = Instant::now();
    child
        .stdin
        .take()
        .unwrap()
        .write_all(event.to_string().as_bytes())
        .unwrap();
    let output = child.wait_with_output().unwrap();
    assert!(output.status.success());
    assert!(
        started.elapsed() < Duration::from_secs(5),
        "policy timeout exceeded its process-level bound: {:?}",
        started.elapsed()
    );
    let decision: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
    assert_eq!(decision["permissionDecision"], "deny");
}

#[test]
fn verifier_distinguishes_pass_fail_and_inconclusive_and_retains_evidence() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    let verifiers = project.path().join(".base/canon/verifiers");
    fs::create_dir_all(&verifiers).unwrap();
    fs::write(
        verifiers.join("pass.md"),
        "---\nid: pass\ndescription: Passing suite.\nchecks:\n  - id: compiler\n    run: [rustc, --version]\n---\n\nPass.\n",
    )
    .unwrap();
    fs::write(
        verifiers.join("fail.md"),
        "---\nid: fail\ndescription: Failing suite.\nchecks:\n  - id: bad-option\n    run: [rustc, --definitely-not-a-real-option]\n---\n\nFail.\n",
    )
    .unwrap();
    fs::write(
        verifiers.join("missing.md"),
        "---\nid: missing\ndescription: Missing tool suite.\nchecks:\n  - id: absent\n    run: [definitely-missing-base-test-program]\n---\n\nMissing.\n",
    )
    .unwrap();
    fs::create_dir_all(project.path().join(".base/runs/verify-demo")).unwrap();

    let passed = success(
        project.path(),
        home.path(),
        &["verify", "pass", "--run", "verify-demo", "--json"],
    );
    let report: serde_json::Value = serde_json::from_slice(&passed.stdout).unwrap();
    assert_eq!(report["verdict"], "pass");
    assert_eq!(report["checks"][0]["output_retained"], false);
    assert!(report["checks"][0]["stdout"].is_null());
    assert!(report["checks"][0]["stdout_bytes"].as_u64().unwrap() > 0);
    assert_eq!(
        report["checks"][0]["stdout_sha256"].as_str().unwrap().len(),
        64
    );
    let evidence = report["evidence_path"].as_str().unwrap();
    assert!(project.path().join(evidence).is_file());
    let retained: serde_json::Value =
        serde_json::from_str(&fs::read_to_string(project.path().join(evidence)).unwrap()).unwrap();
    assert!(retained["checks"][0]["stdout"].is_null());

    for (suite, verdict) in [("fail", "fail"), ("missing", "inconclusive")] {
        let output = base(project.path(), home.path(), &["verify", suite, "--json"]);
        assert!(!output.status.success());
        let report: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
        assert_eq!(report["verdict"], verdict);
    }
}

#[test]
fn verifier_validates_run_before_executing_checks() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    let marker = project.path().join("should-not-exist.txt");
    let marker_literal = marker.to_string_lossy().replace('\'', "''");
    let run = serde_json::to_string(&vec![
        "powershell.exe",
        "-NoProfile",
        "-Command",
        &format!("Set-Content -LiteralPath '{marker_literal}' -Value ran"),
    ])
    .unwrap();
    let verifiers = project.path().join(".base/canon/verifiers");
    fs::create_dir_all(&verifiers).unwrap();
    fs::write(
        verifiers.join("side-effect.md"),
        format!(
            "---\nid: side-effect\ndescription: Side-effect suite.\nchecks:\n  - id: write-marker\n    run: {run}\n---\n\nMust not execute without a valid run.\n"
        ),
    )
    .unwrap();

    let output = base(
        project.path(),
        home.path(),
        &["verify", "side-effect", "--run", "missing-run"],
    );
    assert!(!output.status.success());
    assert!(String::from_utf8_lossy(&output.stderr).contains("no run folder"));
    assert!(!marker.exists());
}

#[test]
fn concurrent_verifications_reserve_distinct_evidence_files() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    let verifiers = project.path().join(".base/canon/verifiers");
    fs::create_dir_all(&verifiers).unwrap();
    fs::write(
        verifiers.join("concurrent.md"),
        "---\nid: concurrent\ndescription: Concurrent evidence suite.\nchecks:\n  - id: compiler\n    run: [rustc, --version]\n---\n\nConcurrent.\n",
    )
    .unwrap();
    fs::create_dir_all(project.path().join(".base/runs/concurrent")).unwrap();

    let spawn = || {
        Command::new(env!("CARGO_BIN_EXE_base"))
            .args([
                "--directory",
                project.path().to_str().unwrap(),
                "--json",
                "verify",
                "concurrent",
                "--run",
                "concurrent",
            ])
            .env("BASE_HOME", home.path())
            .stdout(Stdio::piped())
            .stderr(Stdio::piped())
            .spawn()
            .unwrap()
    };
    let first = spawn();
    let second = spawn();
    let first = first.wait_with_output().unwrap();
    let second = second.wait_with_output().unwrap();
    assert!(first.status.success());
    assert!(second.status.success());
    let first: serde_json::Value = serde_json::from_slice(&first.stdout).unwrap();
    let second: serde_json::Value = serde_json::from_slice(&second.stdout).unwrap();
    assert_ne!(first["evidence_path"], second["evidence_path"]);
    assert!(
        project
            .path()
            .join(first["evidence_path"].as_str().unwrap())
            .is_file()
    );
    assert!(
        project
            .path()
            .join(second["evidence_path"].as_str().unwrap())
            .is_file()
    );
}

#[cfg(windows)]
#[test]
fn verifier_timeout_terminates_the_windows_process_tree() {
    use std::time::Duration;

    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    let marker = project.path().join("surviving-child.txt");
    let marker_literal = marker.to_string_lossy().replace('\'', "''");
    let parent_script = format!(
        "$child = \"Start-Sleep -Seconds 2; Set-Content -LiteralPath ''{marker_literal}'' -Value survived\"; $bytes = [Text.Encoding]::Unicode.GetBytes($child); $encoded = [Convert]::ToBase64String($bytes); Start-Process -WindowStyle Hidden -FilePath powershell.exe -ArgumentList '-NoProfile','-EncodedCommand',$encoded; Start-Sleep -Seconds 10"
    );
    let run = serde_json::to_string(&vec![
        "powershell.exe",
        "-NoProfile",
        "-Command",
        &parent_script,
    ])
    .unwrap();
    let verifiers = project.path().join(".base/canon/verifiers");
    fs::create_dir_all(&verifiers).unwrap();
    fs::write(
        verifiers.join("tree-timeout.md"),
        format!(
            "---\nid: tree-timeout\ndescription: Process-tree timeout suite.\nchecks:\n  - id: tree\n    run: {run}\n    timeout-seconds: 1\n---\n\nTree timeout.\n"
        ),
    )
    .unwrap();

    let output = base(
        project.path(),
        home.path(),
        &["verify", "tree-timeout", "--json"],
    );
    assert!(!output.status.success());
    let report: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
    assert_eq!(report["verdict"], "inconclusive");
    std::thread::sleep(Duration::from_secs(3));
    assert!(
        !marker.exists(),
        "a descendant survived the verifier timeout and wrote {}",
        marker.display()
    );
}

#[cfg(windows)]
#[test]
fn verifier_completion_terminates_background_descendants_that_close_stdio() {
    use std::time::Duration;

    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    let marker = project.path().join("detached-child.txt");
    let marker_literal = marker.to_string_lossy().replace('\'', "''");
    let parent_script = format!(
        "$child = \"[Console]::OpenStandardOutput().Close(); [Console]::OpenStandardError().Close(); Start-Sleep -Seconds 2; Set-Content -LiteralPath ''{marker_literal}'' -Value survived\"; $bytes = [Text.Encoding]::Unicode.GetBytes($child); $encoded = [Convert]::ToBase64String($bytes); Start-Process -WindowStyle Hidden -FilePath powershell.exe -ArgumentList '-NoProfile','-EncodedCommand',$encoded; exit 0"
    );
    let run = serde_json::to_string(&vec![
        "powershell.exe",
        "-NoProfile",
        "-Command",
        &parent_script,
    ])
    .unwrap();
    let verifiers = project.path().join(".base/canon/verifiers");
    fs::create_dir_all(&verifiers).unwrap();
    fs::write(
        verifiers.join("background-cleanup.md"),
        format!(
            "---\nid: background-cleanup\ndescription: Background process cleanup suite.\nchecks:\n  - id: cleanup\n    run: {run}\n    timeout-seconds: 5\n---\n\nCleanup.\n"
        ),
    )
    .unwrap();

    let output = success(
        project.path(),
        home.path(),
        &["verify", "background-cleanup", "--json"],
    );
    let report: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
    assert_eq!(report["verdict"], "pass");
    std::thread::sleep(Duration::from_secs(3));
    assert!(
        !marker.exists(),
        "a background descendant survived command completion and wrote {}",
        marker.display()
    );
}

#[test]
fn canonical_frontmatter_rejects_unknown_fields() {
    let cases = [
        (
            ".base/canon/agents/typo.md",
            "---\nid: typo\ndescription: Typo.\nacess: read-only\n---\n\nAgent.\n",
        ),
        (
            ".base/canon/pipelines/typo.md",
            "---\nid: typo\ndescription: Typo.\nstages:\n  - use: intake\n    verifer: missing\n  - use: record\n---\n\nPipeline.\n",
        ),
        (
            ".base/canon/policies/typo.md",
            "---\nid: typo\ndescription: Typo.\nevent: pre-tool-use\nmode: guard\ncommand: [rustc, --version]\nfail_closed: true\n---\n\nPolicy.\n",
        ),
        (
            ".base/canon/verifiers/typo.md",
            "---\nid: typo\ndescription: Typo.\nchecks:\n  - id: compiler\n    run: [rustc, --version]\n    timeout_seconds: 1\n---\n\nVerifier.\n",
        ),
    ];

    for (path, source) in cases {
        let project = TempDir::new().unwrap();
        let home = TempDir::new().unwrap();
        success(project.path(), home.path(), &["init", "--project"]);
        let path = project.path().join(path);
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, source).unwrap();
        let output = base(project.path(), home.path(), &["check"]);
        assert!(!output.status.success());
        assert!(
            String::from_utf8_lossy(&output.stderr).contains("unknown field"),
            "{}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
}

#[test]
fn malformed_agent_tools_fail_canon_validation() {
    for (tools, expected) in [
        (
            r#"["Read, Write"]"#,
            "printable single tool names without commas",
        ),
        (
            r#"["Read\npermissionMode: bypassPermissions"]"#,
            "printable single tool names without commas",
        ),
        ("[Read, Read]", "repeats tool `Read`"),
    ] {
        let project = TempDir::new().unwrap();
        let home = TempDir::new().unwrap();
        success(project.path(), home.path(), &["init", "--project"]);
        fs::write(
            project.path().join(".base/canon/agents/unsafe.md"),
            format!(
                "---\nid: unsafe\ndescription: Unsafe tools.\ntools: {tools}\n---\n\nUnsafe.\n"
            ),
        )
        .unwrap();

        let output = base(project.path(), home.path(), &["check"]);
        assert!(!output.status.success());
        assert!(
            String::from_utf8_lossy(&output.stderr).contains(expected),
            "{}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
}

#[test]
fn state_points_to_real_work_and_validates_the_handoff_contract() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);
    success(
        project.path(),
        home.path(),
        &["work", "new", "State demo", "--criterion", "Can resume"],
    );
    fs::create_dir_all(project.path().join(".base/runs/state-demo")).unwrap();
    fs::write(
        project.path().join(".base/state/handoff.md"),
        "---\nwork-item: W-0001\nrun: state-demo\n---\n\n# Handoff\n\n## Next action\n\nResume the demo.\n",
    )
    .unwrap();
    success(project.path(), home.path(), &["state", "set", "W-0001"]);
    let shown = success(project.path(), home.path(), &["state", "show", "--json"]);
    let report: serde_json::Value = serde_json::from_slice(&shown.stdout).unwrap();
    assert_eq!(report["current_work"], "W-0001");
    assert_eq!(report["active_run"], "state-demo");
    assert!(
        report["handoff"]
            .as_str()
            .unwrap()
            .contains("Resume the demo")
    );

    fs::write(
        project.path().join(".base/state/handoff.md"),
        "---\nwork-item: W-0001\nrun: state-demo\n---\n\n# Handoff\n\nNo executable next action.\n",
    )
    .unwrap();
    let failed = base(project.path(), home.path(), &["state", "show"]);
    assert!(!failed.status.success());
    assert!(String::from_utf8_lossy(&failed.stderr).contains("## Next action"));

    fs::write(
        project.path().join(".base/state/handoff.md"),
        "---\nwork-item: W-0001\nrun: state-demo\n---\n\n# Handoff\n\n## Next action\n\n## State\n\nStill empty.\n",
    )
    .unwrap();
    let failed = base(project.path(), home.path(), &["state", "show"]);
    assert!(!failed.status.success());
    assert!(String::from_utf8_lossy(&failed.stderr).contains("non-empty"));

    fs::write(
        project.path().join(".base/state/handoff.md"),
        "---\nwork-item: W-0001\nrun: state-demo\n---\n\n# Handoff\n\n## Next action\n\nResume one.\n",
    )
    .unwrap();
    success(
        project.path(),
        home.path(),
        &[
            "work",
            "new",
            "Second state",
            "--criterion",
            "Can resume two",
        ],
    );
    let switched = base(project.path(), home.path(), &["state", "set", "W-0002"]);
    assert!(!switched.status.success());
    assert!(String::from_utf8_lossy(&switched.stderr).contains("belongs to W-0001"));

    success(project.path(), home.path(), &["state", "clear"]);
    assert!(!project.path().join(".base/state/current-work").exists());
    assert!(!project.path().join(".base/state/handoff.md").exists());
}

fn seed_file(path: &Path, content: &str) {
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    fs::write(path, content).unwrap();
}

#[test]
fn ingest_reports_honest_fidelity_buckets_for_a_loose_claude_project() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);

    let src = project.path().join("legacy");
    seed_file(
        &src.join(".claude/agents/analyst.md"),
        "---\nname: analyst\ndescription: Analyze.\ntools: Read\nmodel: opus\n---\n\nAnalyze.\n",
    );
    seed_file(
        &src.join(".claude/settings.json"),
        r#"{"permissions":{"deny":["Bash(git push * main*)"]},"hooks":{"PreToolUse":[{"matcher":"Bash","hooks":[{"type":"command","command":"guard"}]}],"Notification":[{"hooks":[{"type":"command","command":"x"}]}]}}"#,
    );
    seed_file(&src.join(".claude/mystery.txt"), "unrecognized\n");
    seed_file(&src.join("CLAUDE.md"), "# Project\n\nDo good work.\n");

    let output = success(
        project.path(),
        home.path(),
        &["--json", "ingest", src.to_str().unwrap()],
    );
    let report: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
    assert_eq!(report["source_kind"], "loose-claude");
    assert!(report["summary"]["partial"].as_u64().unwrap() >= 1);
    assert!(report["summary"]["unmapped"].as_u64().unwrap() >= 1);

    let artifacts = report["artifacts"].as_array().unwrap();
    // A deny rule surfaces as a standing-denial gate candidate.
    assert!(artifacts.iter().any(|a| a["target"] == "gate"));
    // The Claude-only `model` knob is reported, never silently dropped.
    assert!(artifacts.iter().any(|a| {
        a["claude_only_fields"]
            .as_array()
            .is_some_and(|fields| fields.iter().any(|field| field == "model"))
    }));
    // A PreToolUse command hook maps to a policy; Notification does not.
    assert!(
        artifacts
            .iter()
            .any(|a| a["name"] == "PreToolUse[0]" && a["target"] == "policy")
    );
    assert!(
        artifacts
            .iter()
            .any(|a| a["name"] == "Notification[0]" && a["target"].is_null())
    );
    // The stray file is surfaced for review.
    assert!(
        report["unmapped"]
            .as_array()
            .unwrap()
            .iter()
            .any(|p| p.as_str().unwrap().contains("mystery"))
    );

    // With --run, the inventory and mapping report are retained as run evidence.
    success(project.path(), home.path(), &["work", "new", "Migrate legacy"]);
    fs::create_dir_all(project.path().join(".base/runs/demo-run")).unwrap();
    success(
        project.path(),
        home.path(),
        &["ingest", src.to_str().unwrap(), "--run", "demo-run"],
    );
    let evidence = project.path().join(".base/runs/demo-run/evidence/migration");
    let entries: Vec<_> = fs::read_dir(&evidence).unwrap().flatten().collect();
    assert!(entries.iter().any(|e| e.path().extension().is_some_and(|x| x == "json")));
    assert!(entries.iter().any(|e| e.path().extension().is_some_and(|x| x == "md")));
}

#[test]
fn ingest_detects_a_plugin_manifest_as_the_pack_source() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    success(project.path(), home.path(), &["init", "--project"]);

    let src = project.path().join("mck-plugin");
    seed_file(
        &src.join(".claude-plugin/plugin.json"),
        r#"{"name":"mck","version":"1.2.0","description":"Client system"}"#,
    );
    seed_file(
        &src.join("agents/analyst.md"),
        "---\nname: analyst\ndescription: Analyze.\n---\n\nAnalyze.\n",
    );

    let output = success(
        project.path(),
        home.path(),
        &["--json", "ingest", src.to_str().unwrap()],
    );
    let report: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
    assert_eq!(report["source_kind"], "plugin");
    assert_eq!(report["plugin"]["name"], "mck");
    let artifacts = report["artifacts"].as_array().unwrap();
    assert!(artifacts.iter().any(|a| a["target"] == "pack-manifest"));
    // Root-level members are discovered even without a `.claude/` prefix.
    assert!(artifacts.iter().any(|a| a["name"] == "analyst" && a["target"] == "agent"));
}

#[test]
fn pack_new_scaffolds_and_check_validates_before_adoption() {
    let project = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();

    success(project.path(), home.path(), &["pack", "new", "mck"]);
    let pack_root = home.path().join("canon/packs/mck");
    assert!(pack_root.join("pack.md").is_file());

    let checked = success(
        project.path(),
        home.path(),
        &["--json", "pack", "check", pack_root.to_str().unwrap()],
    );
    let report: serde_json::Value = serde_json::from_slice(&checked.stdout).unwrap();
    assert_eq!(report["pack"], "mck");
    assert_eq!(report["version"], "0.1.0");

    // A second scaffold of the same id is refused.
    let duplicate = base(project.path(), home.path(), &["pack", "new", "mck"]);
    assert!(!duplicate.status.success());

    // A malformed pack fails validation before it can be adopted.
    let bad = project.path().join("badpack");
    seed_file(
        &bad.join("pack.md"),
        "---\nid: bad\nversion: 0.1.0\ndescription: Broken pack.\n---\n\nBody.\n",
    );
    seed_file(&bad.join("agents/broken.md"), "no frontmatter here\n");
    let output = base(
        project.path(),
        home.path(),
        &["pack", "check", bad.to_str().unwrap()],
    );
    assert!(!output.status.success());
}
