use std::collections::BTreeMap;

use anyhow::{Context, Result};
use serde::Serialize;
use serde_json::{Map, Value, json};

use crate::canon::{Agent, AgentAccess, Canon, Pipeline, Policy, PolicyMode, Skill, Source};
use crate::config::{Config, Gate, GateKind, Target};

pub const GENERATED_HEADER: &str = "<!-- generated by base sync — DO NOT EDIT -->";
pub const GENERATED_MARKER: &str = "generated by base sync — DO NOT EDIT";

pub type RenderedFiles = BTreeMap<String, Vec<u8>>;

pub fn render(canon: &Canon, config: &Config) -> Result<RenderedFiles> {
    let mut files = BTreeMap::new();
    for target in &config.targets {
        match target {
            Target::Claude => render_claude(&mut files, canon, config)?,
            Target::Codex => render_codex(&mut files, canon, config)?,
            Target::Copilot => render_copilot(&mut files, canon, config)?,
        }
    }

    // Codex and Copilot both discover the open Agent Skills layout. Emitting it
    // once avoids duplicate generated ownership when both targets are enabled.
    if config.targets.contains(&Target::Codex) || config.targets.contains(&Target::Copilot) {
        for skill in repo_skills(canon) {
            render_skill_tree(&mut files, ".agents/skills", skill);
        }
        for pipeline in repo_pipelines(canon) {
            insert_text(
                &mut files,
                &format!(".agents/skills/{}/SKILL.md", pipeline.meta.id),
                render_pipeline(canon, config, pipeline, PipelineSurface::SharedAgentSkill),
            );
        }
    }
    Ok(files)
}

fn render_claude(files: &mut RenderedFiles, canon: &Canon, config: &Config) -> Result<()> {
    insert_text(
        files,
        "CLAUDE.md",
        render_instructions(canon, config, Target::Claude),
    );

    for agent in repo_agents(canon) {
        insert_text(
            files,
            &format!(".claude/agents/{}.md", agent.meta.id),
            render_claude_agent(agent),
        );
    }
    for skill in repo_skills(canon) {
        render_skill_tree(files, ".claude/skills", skill);
    }
    for pipeline in repo_pipelines(canon) {
        insert_text(
            files,
            &format!(".claude/skills/{}/SKILL.md", pipeline.meta.id),
            render_pipeline(canon, config, pipeline, PipelineSurface::Claude),
        );
    }

    if let Some(settings) = render_claude_settings(canon, config)? {
        files.insert(".claude/settings.json".to_owned(), settings.into_bytes());
    }
    Ok(())
}

fn render_claude_settings(canon: &Canon, config: &Config) -> Result<Option<String>> {
    let denial = has_default_branch_denial(config);
    let artifact_gates = has_artifact_gate(config);
    let mut hooks: BTreeMap<String, Vec<Value>> = BTreeMap::new();

    if denial || artifact_gates {
        let entry = |tools: &[&str]| {
            json!({
                "matcher": target_glob_matcher(tools.iter().copied(), Target::Claude),
                "hooks": [{
                    "type": "command",
                    "command": "base",
                    "args": [
                        "__hook", "pre-tool", "--target", "claude",
                        "--default-branch", config.default_branch
                    ],
                    "timeout": 10,
                    "statusMessage": "Checking base gates"
                }]
            })
        };
        let pre_tool = hooks.entry("PreToolUse".to_owned()).or_default();
        pre_tool.push(entry(&["Bash"]));
        if artifact_gates {
            pre_tool.push(entry(&["Edit", "Write", "NotebookEdit", "apply_patch"]));
        }
        pre_tool.push(entry(&["mcp__github__*"]));
    }

    for policy in repo_policies(canon) {
        let mut group = json!({
            "hooks": [{
                "type": "command",
                "command": "base",
                "args": ["__hook", "policy", policy.meta.id, "--target", "claude"],
                // Give the wrapper time to turn an inner timeout into the
                // policy's declared fail-open/fail-closed result.
                "timeout": policy.meta.timeout_seconds.saturating_add(2),
                "statusMessage": format!("Running base policy {}", policy.meta.id)
            }]
        });
        if !policy.meta.match_tools.is_empty() {
            group["matcher"] = json!(target_glob_matcher(
                policy.meta.match_tools.iter(),
                Target::Claude
            ));
        }
        hooks
            .entry(policy.meta.event.claude_name().to_owned())
            .or_default()
            .push(group);
    }

    if hooks.is_empty() && !denial {
        return Ok(None);
    }
    let mut settings = Map::new();
    settings.insert(
        "$schema".to_owned(),
        json!("https://json.schemastore.org/claude-code-settings.json"),
    );
    settings.insert("hooks".to_owned(), serde_json::to_value(hooks)?);
    if denial {
        settings.insert(
            "permissions".to_owned(),
            json!({
                "deny": [
                    format!("Bash(git push * {}*)", config.default_branch),
                    format!("Bash(git push * HEAD:{0}*)", config.default_branch)
                ]
            }),
        );
    }
    let mut source =
        serde_json::to_string_pretty(&settings).context("cannot serialize Claude settings")?;
    source.push('\n');
    Ok(Some(source))
}

fn render_codex(files: &mut RenderedFiles, canon: &Canon, config: &Config) -> Result<()> {
    insert_text(
        files,
        "AGENTS.md",
        render_instructions(canon, config, Target::Codex),
    );
    for agent in repo_agents(canon) {
        insert_text(
            files,
            &format!(".codex/agents/{}.toml", agent.meta.id),
            render_codex_agent(agent)?,
        );
    }
    if let Some(hooks) = render_codex_hooks(canon, config)? {
        files.insert(".codex/hooks.json".to_owned(), hooks.into_bytes());
    }

    if has_default_branch_denial(config) {
        let branch = starlark_string(&config.default_branch);
        let rules = format!(
            r#"# {GENERATED_MARKER}

prefix_rule(
    pattern = ["git", "push", "origin", "{branch}"],
    decision = "forbidden",
    justification = "base standing denial: push a feature branch and open a review instead",
    match = ["git push origin {branch}"],
)

prefix_rule(
    pattern = ["git", "push", "origin", "HEAD:{branch}"],
    decision = "forbidden",
    justification = "base standing denial: do not push HEAD to the default branch",
    match = ["git push origin HEAD:{branch}"],
)
"#
        );
        files.insert(".codex/rules/base.rules".to_owned(), rules.into_bytes());
    }
    Ok(())
}

fn render_codex_hooks(canon: &Canon, config: &Config) -> Result<Option<String>> {
    let denial = has_default_branch_denial(config);
    let artifact_gates = has_artifact_gate(config);
    let mut hooks: BTreeMap<String, Vec<Value>> = BTreeMap::new();

    if denial || artifact_gates {
        let args = vec![
            "__hook".to_owned(),
            "pre-tool".to_owned(),
            "--target".to_owned(),
            "codex".to_owned(),
            "--default-branch".to_owned(),
            config.default_branch.clone(),
        ];
        let pre_tool = hooks.entry("PreToolUse".to_owned()).or_default();
        pre_tool.push(codex_command(
            &args,
            10,
            Some(&target_glob_matcher(["Bash"], Target::Codex)),
            true,
            config.requires_base.as_deref(),
        ));
        if artifact_gates {
            pre_tool.push(codex_command(
                &args,
                10,
                Some(&target_glob_matcher(
                    ["Edit", "Write", "NotebookEdit", "apply_patch"],
                    Target::Codex,
                )),
                true,
                config.requires_base.as_deref(),
            ));
        }
        pre_tool.push(codex_command(
            &args,
            10,
            Some(&target_glob_matcher(["mcp__github__*"], Target::Codex)),
            true,
            config.requires_base.as_deref(),
        ));
    }

    for policy in repo_policies(canon) {
        let Some(event) = codex_policy_event(policy) else {
            continue;
        };
        let args = vec![
            "__hook".to_owned(),
            "policy".to_owned(),
            policy.meta.id.clone(),
            "--target".to_owned(),
            "codex".to_owned(),
        ];
        let matcher = (!policy.meta.match_tools.is_empty())
            .then(|| target_glob_matcher(policy.meta.match_tools.iter(), Target::Codex));
        hooks
            .entry(event.to_owned())
            .or_default()
            .push(codex_command(
                &args,
                policy.meta.timeout_seconds.saturating_add(2),
                matcher.as_deref(),
                policy.meta.mode == PolicyMode::Guard && policy.meta.fail_closed,
                config.requires_base.as_deref(),
            ));
    }
    if hooks.is_empty() {
        return Ok(None);
    }
    let root = json!({
        "description": "Generated Base lifecycle policies for this repository.",
        "hooks": hooks
    });
    let mut source = serde_json::to_string_pretty(&root).context("cannot serialize Codex hooks")?;
    source.push('\n');
    Ok(Some(source))
}

fn codex_command(
    args: &[String],
    timeout: u64,
    matcher: Option<&str>,
    fail_closed: bool,
    requirement: Option<&str>,
) -> Value {
    let (command, command_windows) = portable_hook_commands(
        args,
        fail_closed,
        Target::Codex,
        "Base hook runtime is missing or incompatible",
        requirement,
    );
    let mut entry = json!({
        "hooks": [{
            "type": "command",
            "command": command,
            "commandWindows": command_windows,
            "timeout": timeout,
            "statusMessage": "Running Base repository policy"
        }]
    });
    if let Some(matcher) = matcher {
        entry["matcher"] = json!(matcher);
    }
    entry
}

#[derive(Serialize)]
struct CodexAgentFile<'a> {
    name: &'a str,
    description: &'a str,
    #[serde(skip_serializing_if = "Option::is_none")]
    sandbox_mode: Option<&'static str>,
    developer_instructions: String,
}

fn render_codex_agent(agent: &Agent) -> Result<String> {
    let mut instructions = agent.body.trim().to_owned();
    if !agent.meta.skills.is_empty() {
        instructions.push_str("\n\nRequired project skills: ");
        instructions.push_str(
            &agent
                .meta
                .skills
                .iter()
                .map(|id| format!("${id}"))
                .collect::<Vec<_>>()
                .join(", "),
        );
        instructions.push('.');
    }
    let file = CodexAgentFile {
        name: &agent.meta.id,
        description: &agent.meta.description,
        sandbox_mode: match agent.meta.access {
            AgentAccess::Inherit => None,
            AgentAccess::ReadOnly => Some("read-only"),
            AgentAccess::WorkspaceWrite => Some("workspace-write"),
        },
        developer_instructions: instructions,
    };
    let mut source = format!("# {GENERATED_MARKER}\n\n");
    source.push_str(&toml::to_string_pretty(&file).context("cannot serialize Codex agent")?);
    Ok(source)
}

fn render_copilot(files: &mut RenderedFiles, canon: &Canon, config: &Config) -> Result<()> {
    insert_text(
        files,
        ".github/copilot-instructions.md",
        render_instructions(canon, config, Target::Copilot),
    );
    for agent in repo_agents(canon) {
        insert_text(
            files,
            &format!(".github/agents/{}.agent.md", agent.meta.id),
            render_copilot_agent(agent),
        );
    }
    for pipeline in repo_pipelines(canon) {
        insert_text(
            files,
            &format!(".github/prompts/{}.prompt.md", pipeline.meta.id),
            render_pipeline(canon, config, pipeline, PipelineSurface::CopilotPrompt),
        );
    }
    if let Some(hooks) = render_copilot_hooks(canon, config)? {
        files.insert(".github/hooks/base.json".to_owned(), hooks.into_bytes());
    }
    Ok(())
}

fn render_copilot_agent(agent: &Agent) -> String {
    let mut output = String::new();
    line(&mut output, "---");
    line(&mut output, &format!("name: {}", agent.meta.id));
    line(
        &mut output,
        &format!("description: {}", yaml_scalar(&agent.meta.description)),
    );
    if agent.meta.access == AgentAccess::ReadOnly {
        line(&mut output, "tools: [read, search]");
    } else if !agent.meta.tools.is_empty() {
        line(
            &mut output,
            &format!("tools: {}", yaml_sequence(&agent.meta.tools)),
        );
    }
    line(&mut output, "---");
    line(&mut output, "");
    line(&mut output, GENERATED_HEADER);
    line(&mut output, "");
    line(&mut output, agent.body.trim());
    if !agent.meta.skills.is_empty() {
        line(&mut output, "");
        line(
            &mut output,
            &format!(
                "Load these project skills before acting: {}.",
                agent
                    .meta
                    .skills
                    .iter()
                    .map(|id| format!("`{id}`"))
                    .collect::<Vec<_>>()
                    .join(", ")
            ),
        );
    }
    if agent.meta.access != AgentAccess::Inherit {
        line(
            &mut output,
            &format!(
                "Access posture: `{}` (Copilot has no portable custom-agent sandbox field, so treat this as a required behavioral constraint).",
                agent_access(agent.meta.access)
            ),
        );
    }
    output
}

fn render_copilot_hooks(canon: &Canon, config: &Config) -> Result<Option<String>> {
    let denial = has_default_branch_denial(config);
    let artifact_gates = has_artifact_gate(config);
    let mut hooks: BTreeMap<String, Vec<Value>> = BTreeMap::new();

    if denial || artifact_gates {
        let args = vec![
            "__hook".to_owned(),
            "pre-tool".to_owned(),
            "--target".to_owned(),
            "copilot".to_owned(),
            "--default-branch".to_owned(),
            config.default_branch.clone(),
        ];
        let pre_tool = hooks.entry("PreToolUse".to_owned()).or_default();
        if denial && !artifact_gates {
            pre_tool.push(copilot_command(
                &args,
                10,
                Some(&target_glob_matcher(["Bash"], Target::Copilot)),
                true,
                config.requires_base.as_deref(),
            ));
        } else {
            pre_tool.push(copilot_command(
                &args,
                10,
                Some(&target_glob_matcher(
                    ["Bash", "Edit", "Write", "NotebookEdit"],
                    Target::Copilot,
                )),
                true,
                config.requires_base.as_deref(),
            ));
        }
        pre_tool.push(copilot_command(
            &args,
            10,
            Some(&target_glob_matcher(["mcp__github__*"], Target::Copilot)),
            true,
            config.requires_base.as_deref(),
        ));
    }

    for policy in repo_policies(canon) {
        let args = vec![
            "__hook".to_owned(),
            "policy".to_owned(),
            policy.meta.id.clone(),
            "--target".to_owned(),
            "copilot".to_owned(),
        ];
        let matcher = (!policy.meta.match_tools.is_empty())
            .then(|| target_glob_matcher(policy.meta.match_tools.iter(), Target::Copilot));
        hooks
            .entry(policy.meta.event.claude_name().to_owned())
            .or_default()
            .push(copilot_command(
                &args,
                policy.meta.timeout_seconds.saturating_add(2),
                matcher.as_deref(),
                policy.meta.mode == PolicyMode::Guard && policy.meta.fail_closed,
                config.requires_base.as_deref(),
            ));
    }
    if hooks.is_empty() {
        return Ok(None);
    }
    let root = json!({ "version": 1, "disableAllHooks": false, "hooks": hooks });
    let mut source =
        serde_json::to_string_pretty(&root).context("cannot serialize Copilot hooks")?;
    source.push('\n');
    Ok(Some(source))
}

fn copilot_command(
    args: &[String],
    timeout: u64,
    matcher: Option<&str>,
    fail_closed: bool,
    requirement: Option<&str>,
) -> Value {
    let (bash, powershell) = portable_hook_commands(
        args,
        fail_closed,
        Target::Copilot,
        "Base hook runtime is missing or incompatible",
        requirement,
    );
    let mut entry = json!({
        "type": "command",
        "bash": bash,
        "powershell": powershell,
        "timeoutSec": timeout
    });
    if let Some(matcher) = matcher {
        entry["matcher"] = json!(matcher);
    }
    entry
}

fn portable_hook_commands(
    args: &[String],
    fail_closed: bool,
    target: Target,
    reason: &str,
    requirement: Option<&str>,
) -> (String, String) {
    let bash_args = args
        .iter()
        .map(|arg| posix_shell_word(arg))
        .collect::<Vec<_>>()
        .join(" ");
    let powershell_args = args
        .iter()
        .map(|arg| powershell_literal(arg))
        .collect::<Vec<_>>()
        .join(" ");
    let mut capability_args = vec![
        "__hook".to_owned(),
        "capabilities".to_owned(),
        "--require-feature".to_owned(),
        args.get(1)
            .cloned()
            .unwrap_or_else(|| "pre-tool".to_owned()),
    ];
    if let Some(requirement) = requirement {
        capability_args.push("--require".to_owned());
        capability_args.push(requirement.to_owned());
    }
    let bash_capabilities = capability_args
        .iter()
        .map(|arg| posix_shell_word(arg))
        .collect::<Vec<_>>()
        .join(" ");
    let powershell_capabilities = capability_args
        .iter()
        .map(|arg| powershell_literal(arg))
        .collect::<Vec<_>>()
        .join(" ");
    let denial = denial_json(target, reason).to_string();
    let bash_denial = posix_shell_word(&denial);
    let powershell_denial = powershell_literal(&denial);
    if fail_closed {
        (
            format!(
                "if command -v base >/dev/null 2>&1 && base {bash_capabilities} >/dev/null 2>&1; then base {bash_args} || printf '%s\\n' {bash_denial}; else printf '%s\\n' {bash_denial}; fi"
            ),
            format!(
                "$b = Get-Command base -ErrorAction SilentlyContinue; if ($b) {{ & base {powershell_capabilities} *> $null; if ($LASTEXITCODE -eq 0) {{ & base {powershell_args}; if ($LASTEXITCODE -ne 0) {{ Write-Output {powershell_denial} }} }} else {{ Write-Output {powershell_denial} }} }} else {{ Write-Output {powershell_denial} }}"
            ),
        )
    } else {
        (
            format!(
                "if command -v base >/dev/null 2>&1 && base {bash_capabilities} >/dev/null 2>&1; then base {bash_args} || true; fi"
            ),
            format!(
                "$b = Get-Command base -ErrorAction SilentlyContinue; if ($b) {{ & base {powershell_capabilities} *> $null; if ($LASTEXITCODE -eq 0) {{ & base {powershell_args} }} }}; exit 0"
            ),
        )
    }
}

fn denial_json(target: Target, reason: &str) -> Value {
    match target {
        Target::Claude | Target::Codex => json!({
            "hookSpecificOutput": {
                "hookEventName": "PreToolUse",
                "permissionDecision": "deny",
                "permissionDecisionReason": reason
            }
        }),
        Target::Copilot => json!({
            "permissionDecision": "deny",
            "permissionDecisionReason": reason
        }),
    }
}

fn render_instructions(canon: &Canon, config: &Config, target: Target) -> String {
    let mut output = String::new();
    line(&mut output, GENERATED_HEADER);
    line(&mut output, "");
    line(&mut output, "# base agentic system");
    line(&mut output, "");
    line(
        &mut output,
        "Canonical definitions compile into this file. Change `.base/canon/` or installed pack inputs and run `base sync`; never edit generated output directly.",
    );

    if !config.packs.is_empty() {
        line(&mut output, "");
        line(&mut output, "## Composition");
        line(&mut output, "");
        line(
            &mut output,
            "Installed packs compose in declaration order; later packs override earlier IDs and `.base/canon/` is the final project overlay:",
        );
        for pack in &config.packs {
            line(
                &mut output,
                &format!(
                    "- `{}` version `{}` — {}",
                    pack.id, pack.version, pack.description
                ),
            );
        }
    }

    line(&mut output, "");
    line(&mut output, "## Rules");
    for rule in canon
        .rules
        .values()
        .filter(|rule| rule.source.repo_resident())
    {
        line(&mut output, "");
        line(&mut output, &format!("### {}", title(&rule.meta.id)));
        line(&mut output, "");
        line(&mut output, rule.body.trim());
    }

    line(&mut output, "");
    line(&mut output, "## Agents");
    line(&mut output, "");
    match target {
        Target::Claude => line(
            &mut output,
            "Native Claude Code subagents are available under `.claude/agents/`.",
        ),
        Target::Codex => line(
            &mut output,
            "Native Codex custom agents are available under `.codex/agents/`.",
        ),
        Target::Copilot => line(
            &mut output,
            "Native GitHub Copilot custom agents are available under `.github/agents/`.",
        ),
    }
    for agent in repo_agents(canon) {
        line(
            &mut output,
            &format!("- **{}** — {}", agent.meta.id, agent.meta.description),
        );
    }

    line(&mut output, "");
    line(&mut output, "## Skills");
    line(&mut output, "");
    for skill in repo_skills(canon) {
        let invocation = match target {
            Target::Claude => format!("`/{}`", skill.meta.id),
            Target::Codex => format!("`${}`", skill.meta.id),
            Target::Copilot => format!("agent skill `{}`", skill.meta.id),
        };
        line(
            &mut output,
            &format!(
                "- {invocation} — {}",
                skill.meta.description.trim_end_matches('.')
            ),
        );
    }

    line(&mut output, "");
    line(&mut output, "## Pipelines");
    line(&mut output, "");
    for pipeline in repo_pipelines(canon) {
        let invocation = match target {
            Target::Claude => format!("`/{}`", pipeline.meta.id),
            Target::Codex => format!("`${}`", pipeline.meta.id),
            Target::Copilot => format!(
                "Agent Skill `${}` or VS Code prompt `.github/prompts/{}.prompt.md`",
                pipeline.meta.id, pipeline.meta.id
            ),
        };
        line(
            &mut output,
            &format!(
                "- {invocation} — {}",
                pipeline.meta.description.trim_end_matches('.')
            ),
        );
    }

    line(&mut output, "");
    line(&mut output, "## Lifecycle policies");
    line(&mut output, "");
    if repo_policies(canon).next().is_none() {
        line(
            &mut output,
            "- No repository lifecycle policies are installed.",
        );
    } else {
        for policy in repo_policies(canon) {
            line(
                &mut output,
                &format!(
                    "- **{}** (`{}` / `{}` / `{}`): {}",
                    policy.meta.id,
                    policy_event(policy),
                    policy_mode(policy.meta.mode),
                    policy_fidelity(policy, target),
                    policy.meta.description
                ),
            );
            if policy_fidelity(policy, target) != "native-hook" {
                line(
                    &mut output,
                    &format!("  - Fallback: {}", policy.body.trim()),
                );
            }
        }
    }

    line(&mut output, "");
    line(&mut output, "## Verifiers");
    line(&mut output, "");
    if !canon
        .verifiers
        .values()
        .any(|suite| suite.source.repo_resident())
    {
        line(&mut output, "- No repository verifier suites are defined.");
    } else {
        for suite in canon
            .verifiers
            .values()
            .filter(|suite| suite.source.repo_resident())
        {
            line(
                &mut output,
                &format!(
                    "- `base verify {}` — {}",
                    suite.meta.id, suite.meta.description
                ),
            );
        }
    }

    line(&mut output, "");
    line(&mut output, "## Gates");
    line(&mut output, "");
    for gate in &config.gates {
        let fidelity = enforcement(gate, target);
        line(
            &mut output,
            &format!("- **{}** (`{fidelity}`): {}", gate.id, gate.description),
        );
    }
    line(
        &mut output,
        &format!(
            "- The repository default branch is `{}`.",
            config.default_branch
        ),
    );

    line(&mut output, "");
    line(&mut output, "## State and knowledge");
    line(&mut output, "");
    line(
        &mut output,
        "- Current work: `base state show`; session context: `base state context`; durable handoff: `.base/state/handoff.md`.",
    );
    line(
        &mut output,
        "- Work items: `.base/work/` (statuses `todo|doing|review|done`; `done` requires a human `pass|fail` verdict); run artifacts: `.base/runs/`; append-only ledger: `.base/history.jsonl`.",
    );
    let knowledge: Vec<(&String, &Source)> = canon
        .knowledge
        .iter()
        .filter(|(_, entry)| entry.source.repo_resident())
        .map(|(path, entry)| (path, &entry.source))
        .collect();
    if knowledge.is_empty() {
        line(
            &mut output,
            "- No canonical knowledge entries are currently available.",
        );
    } else {
        line(&mut output, "- Load canonical knowledge on demand from:");
        for (path, source) in knowledge {
            let location = match &source.pack {
                Some(pack) => format!(".base/packs/{pack}/knowledge/{path}"),
                None => format!(".base/canon/knowledge/{path}"),
            };
            line(&mut output, &format!("  - `{location}`"));
        }
    }
    output
}

fn render_claude_agent(agent: &Agent) -> String {
    let mut output = String::new();
    line(&mut output, "---");
    line(&mut output, &format!("name: {}", agent.meta.id));
    line(
        &mut output,
        &format!("description: {}", yaml_scalar(&agent.meta.description)),
    );
    if !agent.meta.tools.is_empty() {
        line(
            &mut output,
            &format!("tools: {}", agent.meta.tools.join(", ")),
        );
    }
    if !agent.meta.skills.is_empty() {
        line(&mut output, "skills:");
        for skill in &agent.meta.skills {
            line(&mut output, &format!("  - {skill}"));
        }
    }
    if agent.meta.access == AgentAccess::ReadOnly {
        line(&mut output, "permissionMode: plan");
    }
    line(&mut output, "model: inherit");
    line(&mut output, "---");
    line(&mut output, "");
    line(&mut output, GENERATED_HEADER);
    line(&mut output, "");
    line(&mut output, agent.body.trim());
    if agent.meta.access != AgentAccess::Inherit {
        line(&mut output, "");
        line(
            &mut output,
            &format!(
                "Required access posture: `{}`.",
                agent_access(agent.meta.access)
            ),
        );
    }
    output
}

fn render_skill_tree(files: &mut RenderedFiles, root: &str, skill: &Skill) {
    insert_text(
        files,
        &format!("{root}/{}/SKILL.md", skill.meta.id),
        render_skill(skill),
    );
    for (path, bytes) in &skill.resources {
        files.insert(format!("{root}/{}/{path}", skill.meta.id), bytes.clone());
    }
}

fn render_skill(skill: &Skill) -> String {
    let mut output = String::new();
    line(&mut output, "---");
    line(&mut output, &format!("name: {}", skill.meta.id));
    line(
        &mut output,
        &format!("description: {}", yaml_scalar(&skill.meta.description)),
    );
    line(&mut output, "---");
    line(&mut output, "");
    line(&mut output, GENERATED_HEADER);
    line(&mut output, "");
    line(&mut output, skill.body.trim());
    output
}

#[derive(Clone, Copy)]
enum PipelineSurface {
    Claude,
    SharedAgentSkill,
    CopilotPrompt,
}

fn render_pipeline(
    canon: &Canon,
    config: &Config,
    pipeline: &Pipeline,
    surface: PipelineSurface,
) -> String {
    let mut output = String::new();
    line(&mut output, "---");
    match surface {
        PipelineSurface::Claude => {
            line(&mut output, &format!("name: {}", pipeline.meta.id));
            line(
                &mut output,
                &format!("description: {}", yaml_scalar(&pipeline.meta.description)),
            );
            line(&mut output, "disable-model-invocation: true");
            line(&mut output, "argument-hint: <task>");
        }
        PipelineSurface::SharedAgentSkill => {
            line(&mut output, &format!("name: {}", pipeline.meta.id));
            line(
                &mut output,
                &format!(
                    "description: {}",
                    yaml_scalar(&format!(
                        "{} Use when the user explicitly invokes the {} pipeline.",
                        pipeline.meta.description, pipeline.meta.id
                    ))
                ),
            );
        }
        PipelineSurface::CopilotPrompt => {
            line(&mut output, "agent: 'agent'");
            line(
                &mut output,
                &format!("description: {}", yaml_scalar(&pipeline.meta.description)),
            );
        }
    }
    line(&mut output, "---");
    line(&mut output, "");
    line(&mut output, GENERATED_HEADER);
    line(&mut output, "");
    line(
        &mut output,
        &format!("# {} pipeline", title(&pipeline.meta.id)),
    );
    line(&mut output, "");
    line(&mut output, pipeline.body.trim());
    line(&mut output, "");
    match surface {
        PipelineSurface::Claude => line(&mut output, "Task: $ARGUMENTS"),
        PipelineSurface::SharedAgentSkill => line(
            &mut output,
            "Use the task supplied alongside this explicitly invoked skill.",
        ),
        PipelineSurface::CopilotPrompt => line(
            &mut output,
            "Use the user's current request and attached context as the task.",
        ),
    }
    let harness = match surface {
        PipelineSurface::Claude => "Record `harness` as `claude` in the run ledger.",
        PipelineSurface::SharedAgentSkill => {
            "Record the actual runtime, `codex` or `copilot`, as `harness` in the run ledger."
        }
        PipelineSurface::CopilotPrompt => "Record `harness` as `copilot` in the run ledger.",
    };
    line(&mut output, harness);

    for (index, stage_ref) in pipeline.meta.stages.iter().enumerate() {
        let stage = canon
            .stages
            .get(&stage_ref.use_stage)
            .expect("canon was validated before rendering");
        line(&mut output, "");
        line(
            &mut output,
            &format!("## {}. {}", index + 1, title(&stage.meta.id)),
        );
        line(&mut output, "");
        line(&mut output, stage.body.trim());
        if let Some(agent) = &stage_ref.agent {
            line(&mut output, "");
            line(&mut output, &format!("### Assigned agent: {agent}"));
            line(&mut output, "");
            if stage_ref.independent_review {
                line(
                    &mut output,
                    &format!(
                        "Run this stage in a distinct `{agent}` agent context that did not implement the change. If this target cannot provide separate agent execution, report the review as assisted and do not claim independent maker/checker separation."
                    ),
                );
            } else {
                line(
                    &mut output,
                    &format!(
                        "Delegate this stage to the repository agent `{agent}` when native agent delegation is available; otherwise follow that agent's generated contract directly and report the fallback."
                    ),
                );
            }
        }
        if let Some(gate_id) = &stage_ref.gate {
            let gate = config.gate(gate_id).expect("canon gate was validated");
            line(&mut output, "");
            line(&mut output, &format!("### Gate: {}", gate.id));
            line(&mut output, "");
            let prose = if gate.kind == GateKind::StageApproval && gate.satisfied_by.is_some() {
                format!(
                    "STOP after completing this stage. {} Request the verdict by writing `{}` in the run folder describing what needs approval, then stop. The verdict is recorded from outside the session: `base approve <run-slug> {}` (or `--deny`) writes `{}` — a standing directive counts only when recorded that way, with `--note` citing it. Never create the verdict artifact yourself. If the recorded verdict is `denied`, skip to `record` with outcome `aborted`.",
                    gate.description,
                    gate.request_path(),
                    gate.id,
                    gate.approval_path()
                )
            } else {
                format!(
                    "STOP after completing this stage. {} Do not begin the next stage until the user gives explicit approval in this conversation. If approval is denied or unavailable, skip to `record` with outcome `aborted`.",
                    gate.description
                )
            };
            line(&mut output, &prose);
        }
        if let Some(verifier) = &stage_ref.verifier {
            line(&mut output, "");
            line(&mut output, &format!("### Verifier: {verifier}"));
            line(&mut output, "");
            line(
                &mut output,
                &format!(
                    "Run `base verify {verifier} --run <run-slug>`. A `fail` or `inconclusive` verdict is not passing evidence and must be reported before proceeding."
                ),
            );
        }
    }
    output
}

fn repo_agents(canon: &Canon) -> impl Iterator<Item = &Agent> {
    canon
        .agents
        .values()
        .filter(|item| item.source.repo_resident())
}

fn repo_skills(canon: &Canon) -> impl Iterator<Item = &Skill> {
    canon
        .skills
        .values()
        .filter(|item| item.source.repo_resident())
}

fn repo_pipelines(canon: &Canon) -> impl Iterator<Item = &Pipeline> {
    canon
        .pipelines
        .values()
        .filter(|item| item.source.repo_resident())
}

fn repo_policies(canon: &Canon) -> impl Iterator<Item = &Policy> {
    canon
        .policies
        .values()
        .filter(|item| item.source.repo_resident())
}

pub fn enforcement(gate: &Gate, target: Target) -> &'static str {
    match (gate.kind, target) {
        (GateKind::StandingDenial, Target::Claude | Target::Codex | Target::Copilot)
            if gate.id == "never-push-default-branch" =>
        {
            "native-hook"
        }
        (GateKind::StandingDenial, _) => "advisory",
        (GateKind::StageApproval, Target::Claude | Target::Codex | Target::Copilot)
            if gate.satisfied_by.is_some() =>
        {
            // Pending verdicts are mechanically blocked. Routing a denial to
            // an aborted outcome is still a behavioral pipeline contract.
            "hybrid-hook"
        }
        (GateKind::StageApproval, Target::Claude | Target::Codex | Target::Copilot) => "assisted",
    }
}

pub fn policy_fidelity(policy: &Policy, target: Target) -> &'static str {
    match (target, policy.meta.event) {
        // Codex exposes turn `Stop`, not a session-end event. Mapping it would
        // change the lifecycle contract, so Base keeps this policy assisted.
        (Target::Codex, crate::canon::PolicyEvent::SessionEnd) => "assisted",
        (
            Target::Codex,
            crate::canon::PolicyEvent::PreToolUse | crate::canon::PolicyEvent::PostToolUse,
        ) if policy.meta.match_tools.is_empty() => "partial-hook",
        (_, crate::canon::PolicyEvent::PreToolUse | crate::canon::PolicyEvent::PostToolUse)
            if !policy
                .meta
                .match_tools
                .iter()
                .all(|matcher| target_tool_matcher_supported(matcher, target)) =>
        {
            "partial-hook"
        }
        _ => "native-hook",
    }
}

fn target_tool_matcher_supported(matcher: &str, target: Target) -> bool {
    if matcher.starts_with("mcp__") {
        return match target {
            Target::Claude | Target::Codex => true,
            // Copilot sanitizes the current built-in GitHub MCP server to
            // `github-mcp-server-*`. Other server names need an explicit
            // adapter mapping before Base can claim full matcher fidelity.
            Target::Copilot => matcher.starts_with("mcp__github__"),
        };
    }
    match target {
        Target::Codex => matches!(matcher, "Bash" | "apply_patch"),
        Target::Claude | Target::Copilot => matches!(
            matcher,
            "Bash"
                | "Read"
                | "Write"
                | "Edit"
                | "NotebookEdit"
                | "Glob"
                | "Grep"
                | "WebFetch"
                | "WebSearch"
                | "Task"
                | "apply_patch"
        ),
    }
}

pub fn agent_path(id: &str, target: Target) -> String {
    match target {
        Target::Claude => format!(".claude/agents/{id}.md"),
        Target::Codex => format!(".codex/agents/{id}.toml"),
        Target::Copilot => format!(".github/agents/{id}.agent.md"),
    }
}

pub fn skill_path(id: &str, target: Target) -> String {
    match target {
        Target::Claude => format!(".claude/skills/{id}/SKILL.md"),
        Target::Codex | Target::Copilot => format!(".agents/skills/{id}/SKILL.md"),
    }
}

fn has_artifact_gate(config: &Config) -> bool {
    config
        .gates
        .iter()
        .any(|gate| gate.kind == GateKind::StageApproval && gate.satisfied_by.is_some())
}

fn has_default_branch_denial(config: &Config) -> bool {
    config
        .gate("never-push-default-branch")
        .is_some_and(|gate| gate.kind == GateKind::StandingDenial)
}

fn policy_event(policy: &Policy) -> &'static str {
    match policy.meta.event {
        crate::canon::PolicyEvent::SessionStart => "session-start",
        crate::canon::PolicyEvent::PreToolUse => "pre-tool-use",
        crate::canon::PolicyEvent::PostToolUse => "post-tool-use",
        crate::canon::PolicyEvent::SessionEnd => "session-end",
    }
}

fn codex_policy_event(policy: &Policy) -> Option<&'static str> {
    match policy.meta.event {
        crate::canon::PolicyEvent::SessionStart => Some("SessionStart"),
        crate::canon::PolicyEvent::PreToolUse => Some("PreToolUse"),
        crate::canon::PolicyEvent::PostToolUse => Some("PostToolUse"),
        crate::canon::PolicyEvent::SessionEnd => None,
    }
}

/// Compile Base's portable full-name glob semantics to an explicitly anchored
/// regular expression. Host regex syntax is never accepted as canon.
fn glob_matcher<I, S>(globs: I) -> String
where
    I: IntoIterator<Item = S>,
    S: AsRef<str>,
{
    let alternatives = globs
        .into_iter()
        .map(|glob| {
            let mut pattern = String::new();
            for character in glob.as_ref().chars() {
                match character {
                    '*' => pattern.push_str(".*"),
                    '?' => pattern.push('.'),
                    '\\' | '.' | '+' | '(' | ')' | '[' | ']' | '{' | '}' | '^' | '$' | '|' => {
                        pattern.push('\\');
                        pattern.push(character);
                    }
                    _ => pattern.push(character),
                }
            }
            pattern
        })
        .collect::<Vec<_>>()
        .join("|");
    format!("^(?:{alternatives})$")
}

fn target_glob_matcher<I, S>(globs: I, target: Target) -> String
where
    I: IntoIterator<Item = S>,
    S: AsRef<str>,
{
    let mut translated = Vec::<String>::new();
    for glob in globs {
        let glob = glob.as_ref();
        let mapped = match (target, glob) {
            (Target::Codex, "Edit" | "Write" | "NotebookEdit") => "apply_patch".to_owned(),
            (Target::Claude | Target::Copilot, "apply_patch") => "Edit".to_owned(),
            (Target::Copilot, "NotebookEdit") => "Edit".to_owned(),
            (Target::Copilot, value) if value.starts_with("mcp__github__") => format!(
                "github-mcp-server-{}",
                value.trim_start_matches("mcp__github__")
            ),
            _ => glob.to_owned(),
        };
        if !translated.contains(&mapped) {
            translated.push(mapped);
        }
    }
    glob_matcher(&translated)
}

fn policy_mode(mode: PolicyMode) -> &'static str {
    match mode {
        PolicyMode::Context => "context",
        PolicyMode::Guard => "guard",
        PolicyMode::Observe => "observe",
    }
}

fn agent_access(access: AgentAccess) -> &'static str {
    match access {
        AgentAccess::Inherit => "inherit",
        AgentAccess::ReadOnly => "read-only",
        AgentAccess::WorkspaceWrite => "workspace-write",
    }
}

fn insert_text(files: &mut RenderedFiles, path: &str, mut content: String) {
    if !content.ends_with('\n') {
        content.push('\n');
    }
    files.insert(path.to_owned(), content.into_bytes());
}

fn line(output: &mut String, value: &str) {
    output.push_str(value);
    output.push('\n');
}

fn title(id: &str) -> String {
    id.split('-')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => format!("{}{}", first.to_uppercase(), chars.as_str()),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

fn yaml_scalar(value: &str) -> String {
    serde_json::to_string(value).expect("JSON string is valid YAML")
}

fn yaml_sequence(values: &[String]) -> String {
    serde_json::to_string(values).expect("JSON array is valid YAML")
}

fn starlark_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

fn posix_shell_word(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\"'\"'"))
}

fn powershell_literal(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn title_formats_ids() {
        assert_eq!(title("plan-approval"), "Plan Approval");
    }

    #[test]
    fn enforcement_is_honest_per_cell() {
        let config = Config::default();
        let stage = config.gate("plan-approval").unwrap();
        let denial = config.gate("never-push-default-branch").unwrap();
        assert_eq!(enforcement(stage, Target::Claude), "hybrid-hook");
        assert_eq!(enforcement(stage, Target::Codex), "hybrid-hook");
        assert_eq!(enforcement(stage, Target::Copilot), "hybrid-hook");
        let prose_only = Gate {
            satisfied_by: None,
            ..stage.clone()
        };
        assert_eq!(enforcement(&prose_only, Target::Claude), "assisted");
        assert_eq!(enforcement(denial, Target::Claude), "native-hook");
        assert_eq!(enforcement(denial, Target::Codex), "native-hook");
        assert_eq!(enforcement(denial, Target::Copilot), "native-hook");
        let generic = Gate {
            id: "never-delete-production".to_owned(),
            kind: GateKind::StandingDenial,
            description: "Never delete production.".to_owned(),
            satisfied_by: None,
        };
        assert_eq!(enforcement(&generic, Target::Claude), "advisory");
    }

    #[test]
    fn shell_literals_do_not_interpolate() {
        assert_eq!(posix_shell_word("a'b"), "'a'\"'\"'b'");
        assert_eq!(powershell_literal("a'b"), "'a''b'");
    }

    #[test]
    fn portable_globs_compile_to_anchored_regex() {
        assert_eq!(
            glob_matcher(["Edit", "NotebookEdit", "mcp__github__*"]),
            "^(?:Edit|NotebookEdit|mcp__github__.*)$"
        );
        assert_eq!(
            glob_matcher(["tool.with+syntax?"]),
            "^(?:tool\\.with\\+syntax.)$"
        );
    }

    #[test]
    fn mutation_tool_aliases_translate_per_target() {
        assert_eq!(
            target_glob_matcher(["Edit", "NotebookEdit", "apply_patch"], Target::Codex),
            "^(?:apply_patch)$"
        );
        assert_eq!(
            target_glob_matcher(["apply_patch"], Target::Claude),
            "^(?:Edit)$"
        );
        assert_eq!(
            target_glob_matcher(["NotebookEdit", "apply_patch"], Target::Copilot),
            "^(?:Edit)$"
        );
        assert_eq!(
            target_glob_matcher(["mcp__github__*"], Target::Copilot),
            "^(?:github-mcp-server-.*)$"
        );
        assert!(target_tool_matcher_supported(
            "mcp__github__push_files",
            Target::Copilot
        ));
        assert!(!target_tool_matcher_supported(
            "mcp__custom__write",
            Target::Copilot
        ));
    }
}
