use std::collections::BTreeMap;

use anyhow::{Context, Result};
use serde_json::json;

use crate::canon::{Agent, Canon, Layer, Pipeline};
use crate::config::{Config, Gate, GateKind, Target};

pub const GENERATED_HEADER: &str = "<!-- generated by base sync — DO NOT EDIT -->";
pub const GENERATED_MARKER: &str = "generated by base sync — DO NOT EDIT";

pub type RenderedFiles = BTreeMap<String, Vec<u8>>;

pub fn render(canon: &Canon, config: &Config) -> Result<RenderedFiles> {
    let mut files = BTreeMap::new();
    for target in &config.targets {
        match target {
            Target::Claude => render_claude(&mut files, canon, config)?,
            Target::Codex => render_codex(&mut files, canon, config)?,
            Target::Copilot => render_copilot(&mut files, canon, config)?,
        }
    }
    Ok(files)
}

fn render_claude(files: &mut RenderedFiles, canon: &Canon, config: &Config) -> Result<()> {
    insert_text(
        files,
        "CLAUDE.md",
        render_instructions(canon, config, Target::Claude),
    );

    for agent in canon.agents.values() {
        insert_text(
            files,
            &format!(".claude/agents/{}.md", agent.meta.id),
            render_claude_agent(agent),
        );
    }
    for pipeline in canon.pipelines.values() {
        insert_text(
            files,
            &format!(".claude/skills/{}/SKILL.md", pipeline.meta.id),
            render_pipeline(canon, config, pipeline, Target::Claude),
        );
    }

    if has_default_branch_denial(config) {
        let settings = json!({
            "$schema": "https://json.schemastore.org/claude-code-settings.json",
            "permissions": {
                "deny": [
                    format!("Bash(git push * {}*)", config.default_branch),
                    format!("Bash(git push * HEAD:{0}*)", config.default_branch)
                ]
            },
            "hooks": {
                "PreToolUse": [{
                    "matcher": "Bash",
                    "hooks": [{
                        "type": "command",
                        "if": "Bash(git push *)",
                        "command": "base",
                        "args": ["__hook", "claude-pre-tool", "--default-branch", config.default_branch],
                        "timeout": 10,
                        "statusMessage": "Checking base standing denials"
                    }]
                }, {
                    "matcher": "mcp__github__.*",
                    "hooks": [{
                        "type": "command",
                        "command": "base",
                        "args": ["__hook", "claude-pre-tool", "--default-branch", config.default_branch],
                        "timeout": 10,
                        "statusMessage": "Checking base standing denials"
                    }]
                }]
            }
        });
        let mut settings_source =
            serde_json::to_string_pretty(&settings).context("cannot serialize Claude settings")?;
        settings_source.push('\n');
        files.insert(
            ".claude/settings.json".to_owned(),
            settings_source.into_bytes(),
        );
    }
    Ok(())
}

fn render_codex(files: &mut RenderedFiles, canon: &Canon, config: &Config) -> Result<()> {
    insert_text(
        files,
        "AGENTS.md",
        render_instructions(canon, config, Target::Codex),
    );
    for pipeline in canon.pipelines.values() {
        insert_text(
            files,
            &format!(".agents/skills/{}/SKILL.md", pipeline.meta.id),
            render_pipeline(canon, config, pipeline, Target::Codex),
        );
    }

    if has_default_branch_denial(config) {
        let branch = starlark_string(&config.default_branch);
        let rules = format!(
            r#"# {GENERATED_MARKER}

prefix_rule(
    pattern = ["git", "push", "origin", "{branch}"],
    decision = "forbidden",
    justification = "base standing denial: push a feature branch and open a review instead",
    match = ["git push origin {branch}"],
)

prefix_rule(
    pattern = ["git", "push", "origin", "HEAD:{branch}"],
    decision = "forbidden",
    justification = "base standing denial: do not push HEAD to the default branch",
    match = ["git push origin HEAD:{branch}"],
)
"#
        );
        files.insert(".codex/rules/base.rules".to_owned(), rules.into_bytes());
    }
    Ok(())
}

fn render_copilot(files: &mut RenderedFiles, canon: &Canon, config: &Config) -> Result<()> {
    insert_text(
        files,
        ".github/copilot-instructions.md",
        render_instructions(canon, config, Target::Copilot),
    );
    for pipeline in canon.pipelines.values() {
        insert_text(
            files,
            &format!(".github/prompts/{}.prompt.md", pipeline.meta.id),
            render_pipeline(canon, config, pipeline, Target::Copilot),
        );
    }
    Ok(())
}

fn render_instructions(canon: &Canon, config: &Config, target: Target) -> String {
    let mut output = String::new();
    line(&mut output, GENERATED_HEADER);
    line(&mut output, "");
    line(&mut output, "# base agentic system");
    line(&mut output, "");
    line(
        &mut output,
        "Canonical definitions compile into this file. Change `.base/canon/` and run `base sync`; never edit this output directly.",
    );
    line(&mut output, "");
    line(&mut output, "## Rules");
    for rule in canon.rules.values() {
        line(&mut output, "");
        line(&mut output, &format!("### {}", title(&rule.meta.id)));
        line(&mut output, "");
        line(&mut output, rule.body.trim());
    }

    line(&mut output, "");
    line(&mut output, "## Agents");
    line(&mut output, "");
    match target {
        Target::Claude => line(
            &mut output,
            "Claude Code agent definitions are available under `.claude/agents/`.",
        ),
        Target::Codex | Target::Copilot => line(
            &mut output,
            "These are advisory roles. Use their posture when the task calls for it:",
        ),
    }
    for agent in canon.agents.values() {
        line(
            &mut output,
            &format!("- **{}** — {}", agent.meta.id, agent.meta.description),
        );
    }

    line(&mut output, "");
    line(&mut output, "## Pipelines");
    line(&mut output, "");
    for pipeline in canon.pipelines.values() {
        let invocation = match target {
            Target::Claude => format!("`/{}`", pipeline.meta.id),
            Target::Codex => format!("`${}`", pipeline.meta.id),
            Target::Copilot => format!("`.github/prompts/{}.prompt.md`", pipeline.meta.id),
        };
        line(
            &mut output,
            &format!(
                "- {invocation} — {}",
                pipeline.meta.description.trim_end_matches('.')
            ),
        );
    }

    line(&mut output, "");
    line(&mut output, "## Gates");
    line(&mut output, "");
    for gate in &config.gates {
        let fidelity = enforcement(gate, target);
        line(
            &mut output,
            &format!("- **{}** (`{fidelity}`): {}", gate.id, gate.description),
        );
    }
    line(
        &mut output,
        &format!(
            "- The repository default branch is `{}`.",
            config.default_branch
        ),
    );

    line(&mut output, "");
    line(&mut output, "## State and knowledge");
    line(&mut output, "");
    line(
        &mut output,
        "- Work items: `.base/work/` (one folder per item; canonical file `item.md`, statuses todo|doing|review|done); run artifacts: `.base/runs/`; append-only ledger: `.base/history.jsonl`.",
    );
    // Committed surfaces render repo-resident knowledge only (D-014/D-017);
    // global-only entries are adopted by copying, and `base check` reports them.
    let project_knowledge: Vec<&String> = canon
        .knowledge
        .iter()
        .filter(|(_, entry)| entry.source.layer == Layer::Project)
        .map(|(path, _)| path)
        .collect();
    if project_knowledge.is_empty() {
        line(
            &mut output,
            "- No canonical knowledge entries are currently available.",
        );
    } else {
        line(&mut output, "- Load canonical knowledge on demand from:");
        for path in project_knowledge {
            line(&mut output, &format!("  - `.base/canon/knowledge/{path}`"));
        }
    }
    output
}

fn render_claude_agent(agent: &Agent) -> String {
    let mut output = String::new();
    line(&mut output, "---");
    line(&mut output, &format!("name: {}", agent.meta.id));
    line(
        &mut output,
        &format!("description: {}", yaml_scalar(&agent.meta.description)),
    );
    if !agent.meta.tools.is_empty() {
        line(
            &mut output,
            &format!("tools: {}", agent.meta.tools.join(", ")),
        );
    }
    line(&mut output, "model: inherit");
    line(&mut output, "---");
    line(&mut output, "");
    line(&mut output, GENERATED_HEADER);
    line(&mut output, "");
    line(&mut output, agent.body.trim());
    output
}

fn render_pipeline(canon: &Canon, config: &Config, pipeline: &Pipeline, target: Target) -> String {
    let mut output = String::new();
    line(&mut output, "---");
    match target {
        Target::Claude => {
            line(&mut output, &format!("name: {}", pipeline.meta.id));
            line(
                &mut output,
                &format!("description: {}", yaml_scalar(&pipeline.meta.description)),
            );
            line(&mut output, "disable-model-invocation: true");
            line(&mut output, "argument-hint: <task>");
        }
        Target::Codex => {
            line(&mut output, &format!("name: {}", pipeline.meta.id));
            line(
                &mut output,
                &format!(
                    "description: {}",
                    yaml_scalar(&format!(
                        "{} Use when the user explicitly invokes the {} pipeline.",
                        pipeline.meta.description, pipeline.meta.id
                    ))
                ),
            );
        }
        Target::Copilot => {
            line(&mut output, "agent: 'agent'");
            line(
                &mut output,
                &format!("description: {}", yaml_scalar(&pipeline.meta.description)),
            );
        }
    }
    line(&mut output, "---");
    line(&mut output, "");
    line(&mut output, GENERATED_HEADER);
    line(&mut output, "");
    line(
        &mut output,
        &format!("# {} pipeline", title(&pipeline.meta.id)),
    );
    line(&mut output, "");
    line(&mut output, pipeline.body.trim());
    line(&mut output, "");
    match target {
        Target::Claude => line(&mut output, "Task: $ARGUMENTS"),
        Target::Codex => line(
            &mut output,
            "Use the task supplied alongside this explicitly invoked skill.",
        ),
        Target::Copilot => line(
            &mut output,
            "Use the user's current request and attached context as the task.",
        ),
    }
    line(
        &mut output,
        &format!("Record `harness` as `{target}` in the run ledger."),
    );

    for (index, stage_ref) in pipeline.meta.stages.iter().enumerate() {
        let stage = canon
            .stages
            .get(&stage_ref.use_stage)
            .expect("canon was validated before rendering");
        line(&mut output, "");
        line(
            &mut output,
            &format!("## {}. {}", index + 1, title(&stage.meta.id)),
        );
        line(&mut output, "");
        line(&mut output, stage.body.trim());
        if let Some(gate_id) = &stage_ref.gate {
            let gate = config.gate(gate_id).expect("canon gate was validated");
            line(&mut output, "");
            line(&mut output, &format!("### Gate: {}", gate.id));
            line(&mut output, "");
            line(
                &mut output,
                &format!(
                    "STOP after completing this stage. {} Do not begin the next stage until the user gives explicit approval in this conversation. If approval is denied or unavailable, skip to `record` with outcome `aborted`.",
                    gate.description
                ),
            );
        }
    }
    output
}

pub fn enforcement(gate: &Gate, target: Target) -> &'static str {
    match (gate.kind, target) {
        (GateKind::StandingDenial, Target::Claude) if gate.id == "never-push-default-branch" => {
            "enforced"
        }
        (GateKind::StandingDenial, Target::Codex) if gate.id == "never-push-default-branch" => {
            "assisted"
        }
        (GateKind::StandingDenial, _) => "advisory",
        (GateKind::StageApproval, Target::Claude | Target::Codex) => "assisted",
        (GateKind::StageApproval, Target::Copilot) => "advisory",
    }
}

fn has_default_branch_denial(config: &Config) -> bool {
    config
        .gate("never-push-default-branch")
        .is_some_and(|gate| gate.kind == GateKind::StandingDenial)
}

fn insert_text(files: &mut RenderedFiles, path: &str, mut content: String) {
    if !content.ends_with('\n') {
        content.push('\n');
    }
    files.insert(path.to_owned(), content.into_bytes());
}

fn line(output: &mut String, value: &str) {
    output.push_str(value);
    output.push('\n');
}

fn title(id: &str) -> String {
    id.split('-')
        .filter(|part| !part.is_empty())
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(first) => format!("{}{}", first.to_uppercase(), chars.as_str()),
                None => String::new(),
            }
        })
        .collect::<Vec<_>>()
        .join(" ")
}

fn yaml_scalar(value: &str) -> String {
    serde_json::to_string(value).expect("JSON string is valid YAML")
}

fn starlark_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn title_formats_ids() {
        assert_eq!(title("plan-approval"), "Plan Approval");
    }

    #[test]
    fn enforcement_is_honest_per_cell() {
        let config = Config::default();
        let stage = config.gate("plan-approval").unwrap();
        let denial = config.gate("never-push-default-branch").unwrap();
        assert_eq!(enforcement(stage, Target::Claude), "assisted");
        assert_eq!(enforcement(denial, Target::Claude), "enforced");
        assert_eq!(enforcement(denial, Target::Copilot), "advisory");
        let generic = Gate {
            id: "never-delete-production".to_owned(),
            kind: GateKind::StandingDenial,
            description: "Never delete production.".to_owned(),
        };
        assert_eq!(enforcement(&generic, Target::Claude), "advisory");
    }
}
